const APP_ID='preset-compare-migrator';const APP_TITLE='预设更新编辑器';
/* 以下 4 个全局捕获监听原挂 document（面板关闭后仍常驻），现改为命名函数挂到 dialog（见 shell()），随面板销毁自动释放。 */
function onToggleEnabledClick(event){const tag=event.target.closest?.('[data-toggle-enabled]');if(tag){togglePromptEnabled(tag.dataset.side,tag.dataset.toggleEnabled);event.preventDefault();event.stopPropagation();}}
let tavernPresetPickerSide='old';
let tavernPresetPickerData=new Map();
function onTavernPickerClick(event){const target=event.target.closest?.('button');if(!target)return;if(target.dataset.action==='pull-tavern'){tavernPresetPickerSide=target.dataset.side||'old';return;}if(target.dataset.action==='choose-tavern'&&tavernPresetPickerSide==='new'){const preset=tavernPresetPickerData.get(target.dataset.presetName);if(!preset)return;state.new=validate(clone(preset));state.newName=target.dataset.presetName+'.json';state.tavernSource.new=target.dataset.presetName;state.dirty.new=false;state.activeId=null;state.activeSide=null;document.querySelector('[data-tavern-picker]')?.classList.remove('open');hideCompare();rebuildCache();renderAll(false);event.stopImmediatePropagation();}}
const state={old:null,new:null,oldName:'',newName:'',query:{old:'',new:''},filter:{old:'all',new:'all'},activeId:null,activeSide:null,dirty:{old:false,new:false},grouping:{side:null,groupId:null},dragged:{old:new Set(),new:new Set()},modified:{old:new Set(),new:new Set()},history:[],projectId:null,ignoreWhitespace:false,showDiff:false,showSimilarity:false,syncScroll:false,uiTheme:loadUiTheme(),cache:{maps:{old:new Map(),new:new Map()},status:new Map(),ordered:{old:[],new:[]},similarity:new Map(),rows:{old:new Map(),new:new Map()}}};

const DB_NAME='preset-compare-projects',DB_STORE='projects';
state.freeSelect={enabled:false,oldId:null,newId:null};
state.unInjectedCollapsed={old:true,new:true};state.groupCollapsed={};
state.tavernSource={old:null,new:null};
function openProjectDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,2);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(DB_STORE))db.createObjectStore(DB_STORE,{keyPath:'id'});if(!db.objectStoreNames.contains('prefs'))db.createObjectStore('prefs',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
/* 界面开关状态（自由选择/忽略空白/正文差异）持久化到 IndexedDB 的 prefs 仓库，重开插件后保留。 */
async function saveUiPrefs(){try{const db=await openProjectDb();await new Promise((res,rej)=>{const tx=db.transaction('prefs','readwrite');tx.objectStore('prefs').put({id:'ui',freeSelect:state.freeSelect.enabled,ignoreWhitespace:state.ignoreWhitespace,showDiff:state.showDiff,showSimilarity:state.showSimilarity,syncScroll:state.syncScroll});tx.oncomplete=()=>{db.close();res();};tx.onerror=()=>rej(tx.error);});}catch{}}
async function loadUiPrefs(){try{const db=await openProjectDb();const rec=await new Promise((res,rej)=>{const tx=db.transaction('prefs','readonly'),rq=tx.objectStore('prefs').get('ui');rq.onsuccess=()=>res(rq.result);rq.onerror=()=>rej(rq.error);tx.oncomplete=()=>db.close();});if(rec){state.freeSelect.enabled=!!rec.freeSelect;state.ignoreWhitespace=!!rec.ignoreWhitespace;state.showDiff=!!rec.showDiff;state.showSimilarity=!!rec.showSimilarity;state.syncScroll=!!rec.syncScroll;const fs=document.querySelector('[data-free-select]');if(fs)fs.checked=state.freeSelect.enabled;const iw=document.querySelector('[data-ignore-whitespace]');if(iw)iw.checked=state.ignoreWhitespace;const sm=document.querySelector('[data-show-similarity]');if(sm)sm.checked=state.showSimilarity;const ss=document.querySelector('[data-sync-scroll]');if(ss)ss.checked=state.syncScroll;}}catch{}}
async function dbRequest(mode,callback){const db=await openProjectDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,mode),store=tx.objectStore(DB_STORE),request=callback(store);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();});}
async function listProjects(){return(await dbRequest('readonly',store=>store.getAll())).sort((a,b)=>b.updatedAt-a.updatedAt);}
function projectData(name,id){return{id:id||crypto.randomUUID(),name,updatedAt:Date.now(),old:clone(state.old),new:clone(state.new),oldName:state.oldName,newName:state.newName,dragged:{old:[...state.dragged.old],new:[...state.dragged.new]},modified:{old:[...state.modified.old],new:[...state.modified.new]},filter:clone(state.filter)};}
async function saveProject(forceName){let name=forceName||document.querySelector('[data-project-name]')?.value.trim();if(!name)name=prompt('请输入项目名称',state.oldName&&state.newName?state.oldName+' / '+state.newName:'预设编辑项目');if(!name)return;const data=projectData(name,state.projectId);await dbRequest('readwrite',store=>store.put(data));state.projectId=data.id;await refreshProjects();pcmToastr.success('项目已保存');}
async function loadProject(id){const data=await dbRequest('readonly',store=>store.get(id));if(!data)return;state.old=data.old;state.new=data.new;state.oldName=data.oldName||'';state.newName=data.newName||'';state.dragged={old:new Set(data.dragged?.old||[]),new:new Set(data.dragged?.new||[])};state.modified={old:new Set(data.modified?.old||[]),new:new Set(data.modified?.new||[])};state.filter=data.filter||{old:'all',new:'all'};state.projectId=data.id;state.history=[];state.activeId=null;state.activeSide=null;hideCompare();rebuildCache();renderAll(false);await refreshProjects();}
async function deleteProject(id){if(!id||!confirm('确定删除这个已保存项目吗？'))return;await dbRequest('readwrite',store=>store.delete(id));if(state.projectId===id)state.projectId=null;await refreshProjects();}
async function refreshProjects(){const select=document.querySelector('[data-project-select]');if(!select)return;let projects;try{projects=await listProjects();}catch{return;}select.replaceChildren();const empty=el('option','',projects.length?'选择已保存项目':'暂无已保存项目');empty.value='';select.append(empty);for(const project of projects){const option=el('option','',project.name+' · '+new Date(project.updatedAt).toLocaleString());option.value=project.id;option.selected=project.id===state.projectId;select.append(option);}const current=projects.find(x=>x.id===state.projectId),name=document.querySelector('[data-project-name]');if(name&&current)name.value=current.name;}
function pushUndo(action){state.history.push(action);if(state.history.length>50)state.history.shift();updateUndoButton();}
function updateUndoButton(){const button=document.querySelector('[data-action=undo]');if(button)button.disabled=!state.history.length;}
function undoLast(){const action=state.history.pop();if(!action)return;const side=action.side,preset=state[side];if(action.type==='edit'){const index=preset.prompts.findIndex(p=>p.identifier===action.id);if(index>=0)preset.prompts[index]=action.before;state.modified[side]=new Set(action.modifiedBefore);}else if(action.type==='move'){preset.prompts=action.promptOrder.map(id=>action.prompts.get(id)).filter(Boolean);preset.prompt_order=clone(action.promptOrderData);preset.extensions=clone(action.extensionsBefore);state.dragged[side]=new Set(action.draggedBefore);}state.dirty[side]=true;state.activeId=null;hideCompare();rebuildCache();renderAll();updateUndoButton();}

const clone=value=>structuredClone(value);
const ALL_TRIGGERS=['continue','impersonate','normal','quiet','regenerate','swipe'];
const normalizeTrigger=value=>{if(!Array.isArray(value))return[];const sorted=[...value].sort();return sorted.length===ALL_TRIGGERS.length&&ALL_TRIGGERS.every((t,i)=>sorted[i]===t)?[]:sorted;};
const normalizeForCompare=(value,loose)=>{if(Array.isArray(value))return value.map(item=>normalizeForCompare(item,loose));if(value&&typeof value==='object'){const keys=Object.keys(value);if(!keys.includes('injection_trigger'))keys.push('injection_trigger');return Object.fromEntries(keys.sort().map(key=>[key,key==='injection_trigger'?normalizeTrigger(value[key]):normalizeForCompare(value[key],loose)]));}return loose&&typeof value==='string'?value.replace(/\s+/g,''):value;};
const equal=(a,b)=>JSON.stringify(normalizeForCompare(a,state.ignoreWhitespace))===JSON.stringify(normalizeForCompare(b,state.ignoreWhitespace));
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n;}
function btn(text,action,cls,side){const n=el('button','menu_button '+(cls||''),text);n.type='button';n.dataset.action=action;if(side)n.dataset.side=side;return n;}
/* 轻量提示：替代酒馆 toastr（其 CSS 动画/全局容器在移动端较卡），在对话框底部短暂浮现后自动消失。 */
let pcmToastBox=null;
function pcmToast(text,type='info',title){let box=pcmToastBox;if(!box||!box.isConnected)box=pcmToastBox=el('div','pcm-toastbox');const host=document.getElementById(APP_ID+'-dialog')||document.body;if(box.parentNode!==host)host.append(box);const item=el('div','pcm-toast pcm-toast-'+type,(title?title+'：':'')+text);box.append(item);requestAnimationFrame(()=>item.classList.add('in'));const ms=type==='error'?6000:3000;setTimeout(()=>{item.classList.remove('in');setTimeout(()=>item.remove(),260);},ms);}
const pcmToastr={success:(t,ti)=>pcmToast(t,'success',ti),info:(t,ti)=>pcmToast(t,'info',ti),warning:(t,ti)=>pcmToast(t,'warning',ti),error:(t,ti)=>pcmToast(t,'error',ti)};
function validate(data){if(!data||!Array.isArray(data.prompts))throw new Error('不是有效的 SillyTavern OpenAI 预设：缺少 prompts 数组。');const ids=new Set();for(const p of data.prompts){if(!p||typeof p.identifier!=='string'||!p.identifier)throw new Error('存在没有 identifier 的条目。');if(ids.has(p.identifier))throw new Error('条目 ID 重复：'+p.identifier);ids.add(p.identifier);}return data;}
function rebuildCache(){for(const side of ['old','new']){const preset=state[side],map=new Map((preset?.prompts||[]).map(p=>[p.identifier,p]));state.cache.maps[side]=map;const seen=new Set(),out=[],orderEntry=promptOrderEntry(preset),orderEntries=Array.isArray(orderEntry?.order)?orderEntry.order:[];for(const item of orderEntries){const id=typeof item==='string'?item:item?.identifier,p=map.get(id);if(p&&!seen.has(id)){seen.add(id);out.push(p);}}for(const p of preset?.prompts||[])if(!seen.has(p.identifier)){seen.add(p.identifier);out.push(p);}state.cache.ordered[side]=out;}const status=new Map(),ids=new Set([...state.cache.maps.old.keys(),...state.cache.maps.new.keys()]);for(const id of ids){const o=state.cache.maps.old.get(id),n=state.cache.maps.new.get(id);status.set(id,o&&!n?'removed':!o&&n?'added':o&&n&&!equal(withoutEnabled(o),withoutEnabled(n))?'changed':'same');}state.cache.status=status;state.cache.similarity.clear();}
function promptOrderEntry(preset){if(!preset)return null;if(!Array.isArray(preset.prompt_order))preset.prompt_order=[];const prompts=new Set((preset.prompts||[]).map(p=>p.identifier));let best=preset.prompt_order.find(x=>Number(x?.character_id)===100001&&Array.isArray(x.order));if(!best)best=preset.prompt_order.filter(x=>Array.isArray(x?.order)).sort((a,b)=>{const score=x=>x.order.reduce((n,item)=>n+(prompts.has(typeof item==='string'?item:item?.identifier)?1:0),0);return score(b)-score(a)||b.order.length-a.order.length;})[0];return best||null;}
function promptEnabled(side,prompt){const item=promptOrderEntry(state[side])?.order?.find(x=>(typeof x==='string'?x:x?.identifier)===prompt.identifier);return typeof item==='object'&&typeof item.enabled==='boolean'?item.enabled:prompt.enabled!==false;}
const withoutEnabled=prompt=>{if(!prompt)return prompt;const copy={...prompt};delete copy.enabled;return copy;};
function updateEnabledRowVisual(side,id){if(!["all","dragged","modified"].includes(state.filter[side])){renderList(side);return;}const list=document.querySelector('[data-list="'+side+'"]'),row=rowById(list,id);if(!row){renderList(side);return;}const prompt=byId(side).get(id),enabled=prompt?promptEnabled(side,prompt):true;row.classList.toggle('pcm-row-disabled',!enabled);const sw=row.querySelector('.pcm-switch');if(sw){sw.classList.toggle('pcm-op-enabled',enabled);sw.classList.toggle('pcm-op-disabled',!enabled);sw.setAttribute('aria-checked',String(enabled));sw.title=enabled?'已启用':'已禁用';}const otherSide=side==='old'?'new':'old',otherRow=rowById(document.querySelector('[data-list="'+otherSide+'"]'),id);updateRowBadge(row,id,side);updateRowBadge(otherRow,id,otherSide);updateSummary(side);updateSummary(otherSide);}
function togglePromptEnabled(side,id){const prompt=byId(side).get(id);if(!prompt)return;const next=!promptEnabled(side,prompt),entry=promptOrderEntry(state[side]);if(entry){let item=entry.order.find(x=>(typeof x==='string'?x:x?.identifier)===id);if(typeof item==='string'){const index=entry.order.indexOf(item);item={identifier:id,enabled:next};entry.order[index]=item;}else if(item)item.enabled=next;else entry.order.push({identifier:id,enabled:next});}prompt.enabled=next;state.dirty[side]=true;rebuildCache();updateEnabledRowVisual(side,id);if(state.activeId===id)renderCompare();}
function bindEnabledTags(side){document.querySelectorAll('[data-list="'+side+'"] .pcm-op-enabled,[data-list="'+side+'"] .pcm-op-disabled').forEach(tag=>{const row=tag.closest('.pcm-row');if(row){tag.dataset.toggleEnabled=row.dataset.dragId;tag.dataset.side=side;tag.title='Toggle enabled state';}});}
function isInjected(side,prompt){const entry=promptOrderEntry(state[side]);if(!entry?.order?.length)return true;return entry.order.some(x=>(typeof x==='string'?x:x?.identifier)===prompt.identifier);}
function unInjected(side){return(state[side]?.prompts||[]).filter(p=>!isInjected(side,p));}
function appendUnInjectedGroup(side,list,used){const prompts=unInjected(side);if(!prompts.length)return;const collapsed=state.unInjectedCollapsed[side]!==false,group=el('section','pcm-group pcm-uninjected'+(collapsed?' pcm-collapsed':'')),head=el('button','pcm-group-head pcm-uninjected-toggle'),body=el('div','pcm-group-body');head.type='button';head.dataset.action='toggle-uninjected';head.dataset.side=side;head.setAttribute('aria-expanded',String(!collapsed));head.append(el('span','pcm-group-caret',collapsed?'\u25b6':'\u25bc'),el('span','', '未注入'),el('small','',prompts.length+' 条'));body.hidden=collapsed;for(const prompt of prompts)body.append(rowFor(side,prompt,used));group.append(head,body);list.append(group);}
const UI_THEME_KEY='preset-compare-migrator.ui-theme';const UI_THEMES=[['auto','配色：自适应'],['day','配色：日间'],['night','配色：夜间']];const UI_THEME_ICONS={auto:'<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"/><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/></svg>',day:'<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/></svg>',night:'<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg>'};function loadUiTheme(){try{const v=localStorage.getItem(UI_THEME_KEY);return UI_THEMES.some(x=>x[0]===v)?v:'auto';}catch(error){return 'auto';}}function saveUiTheme(v){try{localStorage.setItem(UI_THEME_KEY,v);}catch(error){}}
function applyUiTheme(){const d=document.getElementById(APP_ID+'-dialog');if(!d)return;d.classList.toggle('pcm-theme-day',state.uiTheme==='day');d.classList.toggle('pcm-theme-night',state.uiTheme==='night');}
function cycleUiTheme(){const i=UI_THEMES.findIndex(x=>x[0]===state.uiTheme);state.uiTheme=UI_THEMES[(i+1)%UI_THEMES.length][0];saveUiTheme(state.uiTheme);applyUiTheme();const b=document.querySelector('[data-theme-toggle]');if(b)b.innerHTML=UI_THEME_ICONS[state.uiTheme]||'';}
function installHeaderToggles(){const header=document.querySelector('.pcm-header');if(!header)return;if(!header.querySelector('[data-theme-toggle]')){const tbtn=el('button','menu_button pcm-theme-toggle');tbtn.type='button';tbtn.dataset.themeToggle='';tbtn.innerHTML=UI_THEME_ICONS[state.uiTheme]||'';tbtn.title='切换插件配色：叶子=自适应酒馆 / 太阳=日间 / 月亮=夜间（Gruvbox Dark），选择会自动记住';tbtn.addEventListener('click',cycleUiTheme);header.insertBefore(tbtn,header.lastElementChild);}if(!header.querySelector('[data-free-select]')){const label=el('label','pcm-free-select'),input=el('input');input.type='checkbox';input.dataset.freeSelect='';input.checked=state.freeSelect.enabled;label.append(input,el('span','', '自由选择'));header.insertBefore(label,header.lastElementChild);}if(!header.querySelector('[data-ignore-whitespace]')){const label=el('label','pcm-free-select'),input=el('input');input.type='checkbox';input.dataset.ignoreWhitespace='';input.checked=state.ignoreWhitespace;label.title='忽略仅空白（空格/换行/缩进）不同的差异';label.append(input,el('span','', '忽略空白'));header.insertBefore(label,header.lastElementChild);}if(!header.querySelector('[data-show-similarity]')){const label=el('label','pcm-free-select'),input=el('input');input.type='checkbox';input.dataset.showSimilarity='';input.checked=state.showSimilarity;label.title='同名已修改条目显示正文差异百分比，差异小可放心忽略、差异大重点核对是否为自己的魔改或作者的重要更新';label.append(input,el('span','', '差异程度'));header.insertBefore(label,header.lastElementChild);}if(!header.querySelector('[data-sync-scroll]')){const label=el('label','pcm-free-select'),input=el('input');input.type='checkbox';input.dataset.syncScroll='';input.checked=state.syncScroll;label.title='开启后左右两个列表按渲染顺序对齐滚动，便于逐条对比同一条目';label.append(input,el('span','', '同步滚动'));header.insertBefore(label,header.lastElementChild);}}
/* 全文档 subtree 观察已移除（酒馆流式消息每次 DOM 变动都会触发，拖累宿主页面）：shell() 挂载后直接调 installHeaderToggles()。 */
function onHeaderToggleChange(event){if(event.target.matches?.('[data-free-select]'))setFreeSelect(event.target.checked);if(event.target.matches?.('[data-ignore-whitespace]'))setIgnoreWhitespace(event.target.checked);if(event.target.matches?.('[data-show-similarity]'))setShowSimilarity(event.target.checked);if(event.target.matches?.('[data-sync-scroll]'))setSyncScroll(event.target.checked);if(event.target.matches?.('[data-toggle-diff]')){state.showDiff=event.target.checked;saveUiPrefs();if(state.freeSelect.enabled&&state.freeSelect.oldId&&state.freeSelect.newId)renderFreeCompare();else renderCompare();}}
function onFreeSelectClick(event){if(!state.freeSelect.enabled)return;const button=event.target.closest?.('[data-open][data-side]');if(button&&selectFreePrompt(button.dataset.side,button.dataset.open)){event.preventDefault();event.stopImmediatePropagation();}}
function setFreeSelect(enabled){state.freeSelect={enabled,oldId:null,newId:null};state.activeId=null;saveUiPrefs();hideCompare();renderAll();pcmToastr.info(enabled?'请先选择旧版条目，再选择新版条目':'已关闭自由选择');}
function setIgnoreWhitespace(enabled){state.ignoreWhitespace=enabled;saveUiPrefs();rebuildCache();renderAll();pcmToastr.info(enabled?'已忽略仅空白（空格/换行/缩进）不同的差异':'已恢复逐字精确比对');}
function setShowSimilarity(enabled){state.showSimilarity=enabled;saveUiPrefs();renderAll();pcmToastr.info(enabled?'已显示同名条目正文差异百分比':'已隐藏差异百分比');}
function setSyncScroll(enabled){state.syncScroll=enabled;saveUiPrefs();pcmToastr.info(enabled?(matchMedia('(max-width:900px)').matches?'已开启同步滚动：左右列表按渲染序位对齐（竖排布局下仅位置联动）':'已开启同步滚动：左右列表按渲染序位对齐'):'已关闭同步滚动');}
/* 同步滚动(v1.6.2)：开启后左右列表按 prompt_order 渲染顺序对齐滚动。取源列表视口中心行为锚点，
   换算成其渲染顺序(filtered)中的序位，目标列表滚到同序位条目行(不要求同 id，两侧排序保持一致即可联动)；
   rAF 节流 + guard 吞掉对侧回写触发的事件防死循环；锚点是未注入行/目标序位缺失时静默跳过；面板销毁随 dialog 一起释放。 */
let syncScrollRaf=0,syncScrollGuard=false,syncScrollPair=null;function installSyncScroll(){for(const side of['old','new']){const list=document.querySelector('[data-list="'+side+'"]');if(list&&!list.dataset.syncBound){list.dataset.syncBound='1';list.addEventListener('scroll',onListScroll,{passive:true});}}}function onListScroll(event){if(!state.syncScroll)return;const src=event.currentTarget;if(syncScrollGuard){syncScrollGuard=false;return;}const srcSide=src.dataset.list,otherSide=srcSide==='old'?'new':'old';const other=document.querySelector('[data-list="'+otherSide+'"]');if(!other)return;const r=src.getBoundingClientRect();if(!(r.width>0&&r.height>0))return;let anchor=null;try{const hit=document.elementFromPoint(r.left+Math.min(48,r.width/2),r.top+r.height/2);if(hit){anchor=hit.closest?.('.pcm-row')||null;if(anchor&&anchor.closest('[data-list]')!==src)anchor=null;}}catch{}if(!anchor)return;/* 按渲染顺序(prompt_order+过滤结果)对齐:源列表序位 → 目标列表同序位 */const srcList=filtered(srcSide),idx=srcList.findIndex(p=>p.identifier===anchor.dataset.dragId);if(idx<0)return;const otherList=filtered(otherSide);if(!otherList.length)return;const targetId=otherList[Math.min(idx,otherList.length-1)].identifier;syncScrollPair={other,id:targetId,offset:anchor.getBoundingClientRect().top-r.top};if(!syncScrollRaf)syncScrollRaf=requestAnimationFrame(applySyncScroll);}function applySyncScroll(){syncScrollRaf=0;if(!state.syncScroll)return;const p=syncScrollPair;syncScrollPair=null;if(!p)return;const target=p.other.querySelector('.pcm-row[data-drag-id="'+CSS.escape(p.id)+'"]');if(!target||!target.isConnected)return;const want=p.other.getBoundingClientRect().top+p.offset;syncScrollGuard=true;p.other.scrollTop+=target.getBoundingClientRect().top-want;}
function selectFreePrompt(side,id){if(!state.freeSelect.enabled)return false;if(side==='old'&&state.freeSelect.oldId===id){/* 再次点击已选中的旧版条目=取消选中(连带取消新版) */state.freeSelect.oldId=null;state.freeSelect.newId=null;markFreeSelection();hideCompare();pcmToastr.info('已取消选择旧版条目');return true;}if(side==='new'&&state.freeSelect.newId===id){/* 再次点击已选中的新版条目=取消选中新版 */state.freeSelect.newId=null;markFreeSelection();hideCompare();pcmToastr.info('已取消选择新版条目');return true;}if(!state.freeSelect.oldId){if(side!=='old'){pcmToastr.warning('请先选择旧版条目');return true;}state.freeSelect.oldId=id;markFreeSelection();pcmToastr.info('已选择旧版条目，请选择新版条目');return true;}if(side==='old'){state.freeSelect.oldId=id;state.freeSelect.newId=null;markFreeSelection();hideCompare();pcmToastr.info('已更换旧版条目，请选择新版条目');return true;}state.freeSelect.newId=id;markFreeSelection();renderFreeCompare();return true;}
function markFreeSelection(){for(const side of ['old','new']){const id=state.freeSelect[side+'Id'];document.querySelectorAll('[data-list="'+side+'"] .pcm-row').forEach(row=>{const expect=state.freeSelect.enabled&&row.dataset.dragId===id;row.classList.toggle('pcm-free-selected',expect);if(row.classList.contains('pcm-free-selected')!==expect)state.cache.rows[side].delete(row.dataset.dragId);});}}
function markEnabledTag(row,side,id){const tag=row?.querySelector('.pcm-operation-tags .pcm-op-enabled,.pcm-operation-tags .pcm-op-disabled');if(tag){tag.dataset.toggleEnabled=id;tag.dataset.side=side;tag.title='Toggle enabled state';}}
function byId(side){return state.cache.maps[side];}
/* 同名条目正文差异度（相似度）：仅比对正文 content，Dice 系数(字符 bigram 集合) 0~1，供「差异 x%」徽章。
   尊重「忽略空白」开关（开启时先剥掉所有空白再算）；缓存于 state.cache.similarity，rebuildCache 时仅对 changed 条目惰性计算。 */
function bigramSet(t){const set=new Set();if(t.length<2){if(t)set.add(t);return set;}for(let i=0;i<t.length-1;i++)set.add(t.slice(i,i+2));return set;}
function contentSimilarity(a,b){const norm=t=>state.ignoreWhitespace?String(t||'').replace(/\s+/g,''):String(t||'');const A=bigramSet(norm(a)),B=bigramSet(norm(b));if(!A.size&&!B.size)return 1;let inter=0;for(const g of A)if(B.has(g))inter++;return (2*inter)/(A.size+B.size);}
function similarityOf(id){const c=state.cache.similarity;if(c.has(id))return c.get(id);const o=state.cache.maps.old.get(id),n=state.cache.maps.new.get(id);if(!o||!n)return null;const v=contentSimilarity(o.content,n.content);c.set(id,v);return v;}
function badgeText(id,side){const status=statusOf(id);if(status==='changed'&&state.showSimilarity){const sim=similarityOf(id);if(sim!==null&&sim!==undefined){const o=state.cache.maps.old.get(id),n=state.cache.maps.new.get(id),norm=t=>state.ignoreWhitespace?String(t||'').replace(/\s+/g,''):String(t||''),ol=norm(o&&o.content).length,nl=norm(n&&n.content).length,pct=Math.round(Math.abs(nl-ol)/(Math.max(ol,nl)||1)*100);if(pct>0){const less=(side==='old')===(nl>ol);return(less?'少 ':'多 ')+pct+'%';}return '差异 '+Math.round((1-sim)*100)+'%';}}return statusText[status];}
function statusOf(id){return state.cache.status.get(id)||'same';}
const statusText={removed:'新版已删除',added:'新版新增',changed:'内容已修改',same:'内容相同'};
function ordered(side){const preset=state[side],entry=promptOrderEntry(preset),map=state.cache.maps[side];if(entry&&preset.prompt_order?.[0]!==entry){const index=preset.prompt_order.indexOf(entry);preset.prompt_order.splice(index,1);preset.prompt_order.unshift(entry);}if(entry?.order?.length){const out=[],seen=new Set();for(const item of entry.order){const id=typeof item==='string'?item:item?.identifier,p=map?.get(id);if(p&&!seen.has(id)){seen.add(id);out.push(p);}}for(const p of preset?.prompts||[])if(!seen.has(p.identifier)){seen.add(p.identifier);out.push(p);}state.cache.ordered[side]=out;return out;}const out=(preset?.prompts||[]).slice();state.cache.ordered[side]=out;return out;}
function filtered(side){const q=state.query[side].trim().toLocaleLowerCase(),filter=state.filter[side];return ordered(side).filter(p=>isInjected(side,p)).filter(p=>{const status=statusOf(p.identifier);if(filter==='dragged'&&!state.dragged[side].has(p.identifier))return false;if(filter==='modified'&&!state.modified[side].has(p.identifier))return false;if(!['all','dragged','modified'].includes(filter)&&filter!==status)return false;if(!q)return true;return[p.name,p.identifier,p.content].join('\n').toLocaleLowerCase().includes(q);});}
/* 视窗固定 + 输入法「假拼接」：
   1) 聚焦编辑框即冻结对话框高度（键盘/视口收缩引起的重排被锁死，扩选复制粘贴时视角不跳）；
   2) 键盘高度双通道检测：TauriTavern 的 iframe 视口契约桥会把 --tt-viewport-bottom-inset 等 CSS 变量
      同步到本扩展所在 iframe 的 documentElement 上（直接读即可得键盘占用的底部高度）；普通浏览器则用
      innerHeight-visualViewport.height 的收缩量兜底；
   3) 键盘弹出时在对话框内容末尾垫上等高的空白占位（.pcm-ime-spacer）：内容可滚到底、占位区正好停在键盘上方，
      输入法就像拼接在前端下方、完全不覆盖；键盘收起占位归零。仅在可能为触屏的设备启用。 */
function setupViewportPin(dialog){const touchLikely=matchMedia('(pointer: coarse)').matches||'ontouchstart'in window||navigator.maxTouchPoints>0;if(!touchLikely)return null;let frozen=false,frozenHeight=0,keyboardH=0,ttKeyboard=0,baseInner=0;const isEditable=t=>Boolean(t&&t.closest&&t.closest('.pcm-compare')&&(t.matches('textarea')||t.matches('input')||t.matches('select')));
  /* 键盘高度四通道（取大者，各通道在不适用环境自动归零、互不干扰）：
     1) TauriTavern 宿主 layout API 订阅（官方扩展途径，snapshot.ime.keyboardOffset 即键盘高度）；
     2) CSS 变量（--tt-viewport-bottom-inset / --tt-ime-bottom，TT 契约桥同步）；
     3) 视觉视口差值（原生酒馆/普通浏览器：键盘覆盖模式，布局视口 innerHeight 不变、visualViewport.height 收缩）；
     4) 基准收缩量（interactive-widget=resizes-content：布局视口 innerHeight 随键盘收缩，基准=其滚动最大值）。 */
  const readKeyboardH=()=>{let css=0;try{const cs=getComputedStyle(document.documentElement);css=parseFloat(cs.getPropertyValue('--tt-viewport-bottom-inset'))||parseFloat(cs.getPropertyValue('--tt-ime-bottom'))||0;}catch{}const vv=window.visualViewport,inner=window.innerHeight,diff=vv?Math.max(0,inner-vv.height):0;if(inner>baseInner)baseInner=inner;const shrunk=baseInner>inner?baseInner-inner:0;return Math.max(ttKeyboard,css,diff,shrunk);};
  const spacer=el('div','pcm-ime-spacer');spacer.style.height='0px';dialog.append(spacer);
  const setH=h=>{dialog.style.setProperty('height',h+'px','important');dialog.style.setProperty('max-height',h+'px','important');};
  /* 聚焦即冻结：锁定为键盘弹出前的完整高度。 */
  const freeze=()=>{if(frozen)return;const h=dialog.offsetHeight||window.innerHeight;if(!h)return;setH(h);frozen=true;frozenHeight=h;};
  const unfreeze=()=>{if(!frozen)return;dialog.style.removeProperty('height');dialog.style.removeProperty('max-height');frozen=false;frozenHeight=0;};
  /* 键盘高度变化：更新底部占位（>80px 视为键盘弹出）；聚焦编辑框时把它滚到键盘上方（占位区之前）。 */
  const applyIme=()=>{const h=readKeyboardH();if(h===keyboardH)return;const vv=window.visualViewport;console.debug('[preset-compare-migrator] ime spacer',{keyboard:h,tt:ttKeyboard,inner:window.innerHeight,vv:vv?vv.height:0});keyboardH=h;spacer.style.height=(h>80?h+16:0)+'px';if(h>80){const f=document.activeElement;if(isEditable(f)){const r=f.getBoundingClientRect(),over=r.bottom+h-dialog.clientHeight+16;if(over>0)dialog.scrollTop+=over;}}};
  /* 订阅 TauriTavern 宿主 layout API（顶层窗口 __TAURITAVERN__，与 layout-kit.js 的 getHostWindow 同款查找），
     键盘弹出/收起时宿主会推送 snapshot，ime.keyboardOffset 即键盘占用高度。 */
  try{for(const w of[window,window.parent,window.top]){const layout=w&&w.__TAURITAVERN__?.api?.layout;if(layout&&typeof layout.subscribe==='function'){layout.subscribe(snap=>{const kb=snap?.ime?.keyboardOffset;if(Number.isFinite(kb))ttKeyboard=Math.max(0,kb);applyIme();});break;}}}catch(error){console.warn('[preset-compare-migrator] tt layout subscribe failed',error);}
  dialog.addEventListener('focusin',e=>{if(!isEditable(e.target))return;freeze();applyIme();});
  dialog.addEventListener('focusout',e=>{if(isEditable(e.target)&&!isEditable(e.relatedTarget))unfreeze();});
  const onVv=()=>applyIme();
  window.addEventListener('resize',onVv);if(window.visualViewport)window.visualViewport.addEventListener('resize',onVv);
  /* TauriTavern 桥每帧把 CSS 变量同步到 documentElement，用 MutationObserver 捕获变化；
     500ms 轮询兜底（键盘弹出/收起动画期间视口事件可能缺失）。 */
  let styleObserver=null;try{styleObserver=new MutationObserver(onVv);styleObserver.observe(document.documentElement,{attributes:true,attributeFilter:['style']});}catch{}
  const imeTimer=setInterval(applyIme,500);return()=>{window.removeEventListener('resize',onVv);if(window.visualViewport)window.visualViewport.removeEventListener('resize',onVv);if(styleObserver)styleObserver.disconnect();clearInterval(imeTimer);};}
let viewportPinCleanup=null;
/* 关闭即销毁：面板 DOM/监听/观察者/定时器全部释放，重开由 shell() 重建（state 数据保留，秒恢复）。幂等；
   销毁时强制交互锁归零并 flush 待重载（渲染空守卫跳过，仅同步数据），防锁泄漏卡死后续 PRESET_CHANGED。 */
function destroyPanel(dialog){if(!dialog||!dialog.isConnected)return;stopDragAutoScroll();cleanupTouchDrag();cleanupPointerDrag();clearTimeout(searchTimers.old);clearTimeout(searchTimers.new);searchTimers.old=searchTimers.new=null;touchDrag=null;outerScrollTouch=null;dropMarker=null;dropClass='';dropEndList=null;html5DragPointer=null;pcmInteractionLock=0;for(const [side,name] of [...pcmPendingReload]){pcmPendingReload.delete(side);reloadSideFromTavern(side,name);}if(viewportPinCleanup){try{viewportPinCleanup();}catch{}viewportPinCleanup=null;}tavernPresetPickerData.clear();state.cache.similarity.clear();state.cache.rows.old.clear();state.cache.rows.new.clear();dialog.remove();}
/* 重开恢复：销毁重建后从 state 还原搜索词/筛选并填列表（勾选框由 installHeaderToggles 建时初始化）；rAF 先出框架再渲染。 */
function restorePanelState(dialog){if(!state.old&&!state.new)return;for(const side of['old','new']){const input=dialog.querySelector('[data-search="'+side+'"]');if(input)input.value=state.query[side];const sel=dialog.querySelector('[data-filter="'+side+'"]');if(sel)sel.value=state.filter[side];}requestAnimationFrame(()=>{if(dialog.isConnected)renderAll(false);});}
function shell(){let d=document.getElementById(APP_ID+'-dialog');if(d)return d;d=el('dialog','pcm-dialog');d.id=APP_ID+'-dialog';const app=el('div','pcm-app'),header=el('header','pcm-header'),title=el('div');title.append(el('h2','', '预设条目对比与迁移'),el('p','', '默认只显示列表，点击条目后展开对比'));const project=el('div','pcm-project-bar');const name=el('input');name.placeholder='项目名称';name.dataset.projectName='';const select=el('select');select.dataset.projectSelect='';project.append(name,btn('保存项目','save-project'),btn('保存修改','save-changes','pcm-primary'),select,btn('加载','load-project'),btn('删除项目','delete-project'),btn('撤回','undo'));header.append(title,project,btn('×','close','pcm-close'));app.append(header);const lists=el('section','pcm-lists');lists.append(column('old','旧版预设'),column('new','新版预设'));app.append(lists);const detail=el('section','pcm-compare pcm-hidden');detail.dataset.compare='';app.append(detail);d.append(app);d.addEventListener('click',onClick);d.addEventListener('change',onChange);d.addEventListener('input',onInput);d.addEventListener('dragstart',onDragStart);d.addEventListener('dragover',onDragOver);d.addEventListener('drop',onDrop);d.addEventListener('dragend',onDragEnd);d.addEventListener('touchstart',onOuterScrollTouchStart,{passive:true,capture:true});d.addEventListener('touchmove',onOuterScrollTouchMove,{passive:false,capture:true});d.addEventListener('touchend',onOuterScrollTouchEnd,{passive:true,capture:true});d.addEventListener('touchcancel',onOuterScrollTouchEnd,{passive:true,capture:true});d.addEventListener('touchstart',onTouchStart,{passive:true});d.addEventListener('touchmove',onTouchMove,{passive:false});d.addEventListener('touchend',onTouchEnd,{passive:false});d.addEventListener('touchcancel',onTouchCancel,{passive:true});d.addEventListener('pointerdown',onRowPointerDown);d.addEventListener('pointermove',onRowPointerMove);d.addEventListener('pointerup',onRowPointerUp);d.addEventListener('pointercancel',onRowPointerCancel);d.addEventListener('touchstart',onTouchContactChange,{passive:true,capture:true});d.addEventListener('touchend',onTouchContactChange,{passive:true,capture:true});d.addEventListener('touchcancel',onTouchContactChange,{passive:true,capture:true});d.addEventListener('focusin',e=>{if(isCompareEditable(e.target))pcmLock();});d.addEventListener('focusout',e=>{if(isCompareEditable(e.target)&&!isCompareEditable(e.relatedTarget))pcmUnlock();});d.addEventListener('click',onToggleEnabledClick,true);d.addEventListener('click',onTavernPickerClick,true);d.addEventListener('change',onHeaderToggleChange,true);d.addEventListener('click',onFreeSelectClick,true);d.addEventListener('close',()=>destroyPanel(d));document.body.append(d);viewportPinCleanup=setupViewportPin(d);installHeaderToggles();installSyncScroll();refreshProjects();updateUndoButton();return d;}
function column(side,title){const pane=el('section','pcm-pane');const head=el('header','pcm-pane-head');const info=el('div');info.append(el('h3','',title));const filename=el('span','', '尚未导入');filename.dataset.fileName=side;info.append(filename);const actions=el('div','pcm-actions');const importLabel=el('label','menu_button pcm-import','导入');const input=el('input');input.type='file';input.accept='.json,application/json';input.dataset.file=side;importLabel.append(input);actions.append(btn('酒馆预设','pull-tavern','',side));actions.append(importLabel,btn('保存','save-tavern','',side),btn('导出','export','pcm-primary',side));head.append(info,actions);pane.append(head);const tools=el('div','pcm-tools');const search=el('input');search.type='search';search.placeholder='搜索名称、ID 或正文';search.dataset.search=side;const select=el('select');select.dataset.filter=side;[['all','全部'],['changed','内容有差异'],['removed','新版已删除'],['added','新版新增'],['same','相同'],['dragged','已拖拽'],['modified','已手动修改']].forEach(x=>{const o=el('option','',x[1]);o.value=x[0];select.append(o);});tools.append(search,select);pane.append(tools);const summary=el('div','pcm-summary','导入后显示条目');summary.dataset.summary=side;pane.append(summary);const list=el('div','pcm-list');list.dataset.list=side;pane.append(list);return pane;}
async function loadFile(side,file){try{state[side]=validate(JSON.parse(await file.text()));state[side+'Name']=file.name;state.tavernSource[side]=null;state.dirty[side]=false;state.activeId=null;state.activeSide=null;hideCompare();rebuildCache();renderAll(false);}catch(e){pcmToastr.error(e.message,'导入失败');}}
function renderAll(keepScroll=true){if(!document.getElementById(APP_ID+'-dialog'))return;renderList('old',keepScroll);renderList('new',keepScroll);if(state.freeSelect.enabled&&state.freeSelect.oldId&&state.freeSelect.newId)renderFreeCompare();else if(state.activeId)renderCompare();}
function createPromptRow(side,p){const status=statusOf(p.identifier),enabled=promptEnabled(side,p),groupState=getBaiBaiGroupState(state[side]),selectedForGroup=state.grouping.side===side&&String(groupState?.prompts?.[p.identifier]?.groupId||'')===String(state.grouping.groupId||''),selectedForFree=state.freeSelect.enabled&&state.freeSelect[side+'Id']===p.identifier,row=el('article','pcm-row'+(enabled?'':' pcm-row-disabled')+(p.identifier===state.activeId?' active':'')+(selectedForGroup?' pcm-group-selected':'')+(selectedForFree?' pcm-free-selected':'')),open=el('button','pcm-open');/* 行不带 draggable：桌面拖拽全走指针路径；WebView2(TauriTavern) 下 draggable=true 会在指针移动时启动原生 DnD 手势，dragstart 不触发却把 pointer 流用 pointercancel 掐死 → 拖拽秒退（v1.4.6 教训）。 */row.dataset.dragId=p.identifier;row.dataset.dragSide=side;open.type='button';open.dataset.open=p.identifier;open.dataset.side=side;const title=el('span','pcm-row-title');title.append(el('span','pcm-name',p.name||'(未命名)'));const tags=el('span','pcm-operation-tags');const enabledSwitch=el('span','pcm-switch '+(enabled?'pcm-op-enabled':'pcm-op-disabled'));enabledSwitch.setAttribute('role','switch');enabledSwitch.setAttribute('aria-checked',String(enabled));enabledSwitch.title=enabled?'已启用':'已禁用';const switchTrack=el('span','pcm-switch-track');switchTrack.append(el('span','pcm-switch-knob'));enabledSwitch.append(switchTrack);tags.append(enabledSwitch);if(state.dragged[side].has(p.identifier))tags.append(el('span','pcm-op-tag pcm-op-dragged','已拖拽'));if(state.modified[side].has(p.identifier))tags.append(el('span','pcm-op-tag pcm-op-modified','已修改'));title.append(tags);open.append(title,el('code','',p.identifier));const rowActions=el('span','pcm-row-actions'),dupBtn=el('button','pcm-row-action','⧉'),delBtn=el('button','pcm-row-action pcm-row-del','🗑');dupBtn.type='button';dupBtn.title='复制此条目';dupBtn.dataset.action='duplicate-prompt';dupBtn.dataset.side=side;dupBtn.dataset.id=p.identifier;delBtn.type='button';delBtn.title='删除此条目';delBtn.dataset.action='delete-prompt';delBtn.dataset.side=side;delBtn.dataset.id=p.identifier;rowActions.append(dupBtn,delBtn);row.append(open,rowActions,el('span','pcm-badge pcm-'+status,badgeText(p.identifier,side)));return row;}
/* 行级 DOM 复用（仿 paintBackdrop 的 _k 键控）：渲染键必须覆盖 createPromptRow 的全部视觉状态，改 createPromptRow 时同步改 rowKey；
   复用前剥掉拖拽临时类防脏；renderList 每轮 prune 未命中项，删除条目后不泄漏缓存。 */
function rowKey(side,p){const groupState=getBaiBaiGroupState(state[side]);return[p.identifier,statusOf(p.identifier),promptEnabled(side,p),p.identifier===state.activeId,state.grouping.side===side&&String(groupState?.prompts?.[p.identifier]?.groupId||'')===String(state.grouping.groupId||''),state.freeSelect.enabled&&state.freeSelect[side+'Id']===p.identifier,state.dragged[side].has(p.identifier),state.modified[side].has(p.identifier),badgeText(p.identifier,side),p.name||''].join('|');}
function rowFor(side,p,used){if(used)used.add(p.identifier);const key=rowKey(side,p),cache=state.cache.rows[side],cached=cache.get(p.identifier);if(cached&&cached._k===key){cached.classList.remove('pcm-drop-before','pcm-drop-after','pcm-dragging');return cached;}const row=createPromptRow(side,p);row._k=key;cache.set(p.identifier,row);return row;}
function groupMeta(side){const groupState=getBaiBaiGroupState(state[side]);if(!groupState?.groups?.length)return null;return{state:groupState,groups:new Map(groupState.groups.map(group=>[String(group.id),group]))};}
function renderInjectedList(side,used){const preset=state[side],list=document.querySelector('[data-list="'+side+'"]'),summary=document.querySelector('[data-summary="'+side+'"]');if(!list)return;list.replaceChildren();const pane=list.closest('.pcm-pane');if(!preset){pane?.classList.remove('pcm-loaded');summary.textContent='导入后显示条目';return;}pane?.classList.add('pcm-loaded');document.querySelector('[data-file-name="'+side+'"]').textContent=state[side+'Name'];const prompts=filtered(side),counts={changed:0,removed:0,added:0,same:0};ordered(side).forEach(p=>counts[statusOf(p.identifier)]++);summary.textContent=preset.prompts.length+' 条 · 修改 '+counts.changed+' · '+(side==='old'?'新版删除 '+counts.removed:'新增 '+counts.added)+(state.dirty[side]?' · 有未导出修改':'');const meta=groupMeta(side);if(!meta){for(const p of prompts)list.append(rowFor(side,p,used));return;}list.append(btn('新建分组','new-group','pcm-new-group',side));const groupCounts=new Map();for(const cp of prompts){const rg2=meta.state.prompts?.[cp.identifier]?.groupId,g2=rg2&&meta.groups.has(String(rg2))?String(rg2):'';const k2=g2||'__ungrouped__';groupCounts.set(k2,(groupCounts.get(k2)||0)+1);}let currentKey=Symbol('start'),currentBody=null,currentCollapsed=false;for(const prompt of prompts){const rawGroupId=meta.state.prompts?.[prompt.identifier]?.groupId,groupId=rawGroupId&&meta.groups.has(String(rawGroupId))?String(rawGroupId):'',key=groupId||'__ungrouped__';if(key!==currentKey){currentKey=key;const groupData=groupId?meta.groups.get(groupId):null,gk='g:'+side+':'+key;currentCollapsed=!!state.groupCollapsed[gk];const group=el('section','pcm-group'+(groupId?'':' pcm-ungrouped')+(currentCollapsed?' pcm-collapsed':''));if(groupId){group.dataset.groupId=groupId;group.dataset.groupSide=side;}const head=el('header','pcm-group-head'),toggle=el('button','pcm-group-toggle'),title=el('span','pcm-group-title',groupData?.name||'\u672a\u5206\u7ec4'),actions=el('span','pcm-group-actions');toggle.type='button';toggle.dataset.action='toggle-group';toggle.dataset.side=side;toggle.dataset.groupKey=gk;toggle.setAttribute('aria-expanded',String(!currentCollapsed));toggle.append(el('span','pcm-group-caret',currentCollapsed?'\u25b6':'\u25bc'),title,el('small','',String(groupCounts.get(key)||0)+' \u6761'));if(groupId){actions.append(btn('\u91cd\u547d\u540d','rename-group','',side),btn('\u5220\u9664','delete-group','',side));if(state.grouping.side===side&&String(state.grouping.groupId)===groupId)actions.append(btn('\u5b8c\u6210\u5206\u7ec4','finish-group','pcm-group-finish',side));}head.append(toggle,actions);group.append(head);currentBody=el('div','pcm-group-body');currentBody.hidden=currentCollapsed;group.append(currentBody);list.append(group);}if(!currentCollapsed)currentBody.append(rowFor(side,prompt,used));}}
function renderList(side,keepScroll=true){const list=document.querySelector('[data-list="'+side+'"]');if(!list)return;const st=list.scrollTop,used=new Set();try{renderInjectedList(side,used);appendUnInjectedGroup(side,list,used);}finally{const cache=state.cache.rows[side];for(const id of[...cache.keys()])if(!used.has(id))cache.delete(id);}bindEnabledTags(side);list.scrollTop=keepScroll?st:0;}
function hideCompare(){const detail=document.querySelector('[data-compare]');if(detail){detail.classList.add('pcm-hidden');detail.replaceChildren();}}
function valueText(value){if(value===undefined)return'此版本没有该条目';return typeof value==='string'?value:JSON.stringify(value,null,2);}
/* 字符级 diff：先做行级比对，再把相邻「删除块+新增块」配对成行对，对每对做行内字符级 Myers diff，只高亮真正变化的字符而非整行标红。公共前后缀裁剪 + Myers O(ND)，相似文本近零分配；多重阈值保护（乘积/总长度/编辑距离上限）防超长文本在手机端内存膨胀，超限自动退化为整段标记。 */
const LINE_DIFF_LIMIT=200000,CHAR_DIFF_LIMIT=40000,DIFF_MAX_SEQ=4000,MYERS_MAX_D=800;
function myers(a,b){const n=a.length,m=b.length;if(!n)return b.map(x=>['+',x]);if(!m)return a.map(x=>['-',x]);const off=n+m,W=2*off+1;let v=new Int32Array(W);const trace=[];let D=-1;for(let d=0;d<=off;d++){if(d>MYERS_MAX_D)return null;trace.push(v);const nv=v.slice();for(let k=-d;k<=d;k+=2){let x=(k===-d||(k!==d&&nv[k-1+off]<nv[k+1+off]))?nv[k+1+off]:nv[k-1+off]+1,y=x-k;while(x<n&&y<m&&a[x]===b[y]){x++;y++;}nv[k+off]=x;if(x>=n&&y>=m){D=d;break;}}v=nv;if(D>=0)break;}const ops=[];let x=n,y=m;for(let d=D;d>0;d--){const vv=trace[d],k=x-y,pk=(k===-d||(k!==d&&vv[k-1+off]<vv[k+1+off]))?k+1:k-1,px=vv[pk+off],py=px-pk;while(x>px&&y>py){ops.push([' ',a[x-1]]);x--;y--;}if(x===px){ops.push(['+',b[y-1]]);y--;}else{ops.push(['-',a[x-1]]);x--;}}while(x>0&&y>0){ops.push([' ',a[x-1]]);x--;y--;}ops.reverse();return ops;}
function diffSeq(a,b,limit){let s=0;const min=Math.min(a.length,b.length);while(s<min&&a[s]===b[s])s++;let ea=a.length,eb=b.length;while(ea>s&&eb>s&&a[ea-1]===b[eb-1]){ea--;eb--;}const ops=[];for(let i=0;i<s;i++)ops.push([' ',a[i]]);const ma=ea-s,mb=eb-s;let mid=null;if(ma>0&&mb>0&&ma*mb<=limit&&ma+mb<=DIFF_MAX_SEQ)mid=myers(a.slice(s,ea),b.slice(s,eb));if(mid)for(let i=0;i<mid.length;i++)ops.push(mid[i]);else{for(let i=s;i<ea;i++)ops.push(['-',a[i]]);for(let j=s;j<eb;j++)ops.push(['+',b[j]]);}for(let i=ea;i<a.length;i++)ops.push([' ',a[i]]);return ops;}
function diffLines(oldText,newText){return diffSeq(String(oldText).split('\n'),String(newText).split('\n'),LINE_DIFF_LIMIT);}
function charOps(oldLine,newLine){const ops=diffSeq(Array.from(oldLine),Array.from(newLine),CHAR_DIFF_LIMIT),segs=[];for(let i=0;i<ops.length;i++){const t=ops[i][0],ch=ops[i][1],last=segs[segs.length-1];if(last&&last.t===t)last.text+=ch;else segs.push({t,text:ch});}return segs;}
function buildRows(ops){const rows=[];let i=0;const n=ops.length;while(i<n){if(ops[i][0]===' '){rows.push({t:' ',segs:[{t:' ',text:ops[i][1]}]});i++;continue;}const dels=[],ins=[];while(i<n&&ops[i][0]==='-'){dels.push(ops[i][1]);i++;}while(i<n&&ops[i][0]==='+'){ins.push(ops[i][1]);i++;}const pair=Math.min(dels.length,ins.length),paired=[];for(let k=0;k<pair;k++)paired.push(charOps(dels[k],ins[k]));for(let k=0;k<dels.length;k++)rows.push({t:'-',segs:k<pair?paired[k]:[{t:'-',text:dels[k]}]});for(let k=0;k<ins.length;k++)rows.push({t:'+',segs:k<pair?paired[k]:[{t:'+',text:ins[k]}]});}return rows;}
function appendDiff(head){const tog=el('label','pcm-free-select pcm-diff-toggle'),cb=el('input');cb.type='checkbox';cb.checked=state.showDiff;cb.dataset.toggleDiff='';tog.append(cb,el('span','','正文差异'));head.append(tog);}
/* 保存回酒馆预设本体（参考 JS-Slash-Runner 的 updatePresetWith 思路）：先把改动同步进酒馆内存中的预设对象
   （getCompletionPresetByName 返回 openai_settings 里的实时引用，改它即时生效），再 savePreset 持久化到预设文件。
   仅对「酒馆预设」载入的一侧有效；本地文件无法被浏览器原地覆盖，需用「导出」。 */
async function saveSideToTavern(side){const name=state.tavernSource[side],preset=state[side];if(!preset){pcmToast('请先导入'+(side==='old'?'旧版':'新版')+'预设','warning');return;}if(!name){pcmToast('该预设来自本地文件，无法原地写回，请用「导出」保存','warning');return;}try{const module=await import('/scripts/preset-manager.js'),manager=module.getPresetManager?.('openai');if(!manager||typeof manager.savePreset!=='function')throw new Error('当前酒馆版本未提供预设保存接口');
/* 用 state 的克隆保存，不用 skipUpdate：让 ST 自己执行 updateList（更新 openai_settings 内存列表并走酒馆 UI 刷新事件链，
   官方版与 TauriTavern 版行为一致），酒馆自身与我们的前端拿到的都是最新数据。 */
await manager.savePreset(name,clone(preset));
/* 前端按「重新从酒馆载入」逻辑主动刷新一次（不依赖事件链时序）。 */
reloadSideFromTavern(side,name);
pcmToast('已保存回酒馆预设「'+name+'」','success');}catch(error){console.error('[preset-compare-migrator] save to tavern failed',error);pcmToast('保存回酒馆失败：'+error.message,'error');}}
/* 按名从 preset-manager 内存列表读取预设（重实现 getCompletionPresetByName，兼容数组/对象两种 names 形态，
   官方版与 TauriTavern 版通用，不依赖酒馆助手）。 */
function readPresetByName(manager,name){try{const {presets,preset_names}=manager.getPresetList();let index=-1;if(Array.isArray(preset_names)){index=preset_names.indexOf(name);}else if(preset_names&&typeof preset_names==='object'&&preset_names[name]!==undefined){index=Number(preset_names[name]);}if(index>=0&&index<presets.length)return presets[index];}catch(error){console.warn('[preset-compare-migrator] read preset failed',error);}return null;}
/* 保存后/酒馆事件后按名重载预设到对应面板：从 preset-manager 内存列表读最新对象，刷新前端状态。 */
async function reloadSideFromTavern(side,name){try{const module=await import('/scripts/preset-manager.js'),manager=module.getPresetManager?.('openai');const fresh=manager?readPresetByName(manager,name):null;if(!fresh)return;state[side]=validate(clone(fresh));state[side+'Name']=name+'.json';state.dirty[side]=false;state.modified[side].clear();state.dragged[side].clear();rebuildCache();renderAll();}catch(error){console.warn('[preset-compare-migrator] reload preset failed',error);}}
/* 交互锁（自身鲁棒性，不针对特定插件）：长按拖拽/HTML5拖拽/编辑聚焦等精细操作期间 +1；期间若酒馆自身或任意第三方插件触发 PRESET_CHANGED，不立即 reload 重建 DOM（会把正在操作的行变成游离节点导致命中错位/跳条目），而是记入待重载表，操作全部结束（锁归零）后统一同步一次。 */
let pcmInteractionLock=0,html5DragLock=false;const pcmPendingReload=new Map();function pcmLock(){pcmInteractionLock++;}function pcmUnlock(){pcmInteractionLock=Math.max(0,pcmInteractionLock-1);if(pcmInteractionLock===0){for(const [side,name] of [...pcmPendingReload]){pcmPendingReload.delete(side);reloadSideFromTavern(side,name);}}}function requestSideReload(side,name){if(pcmInteractionLock>0){pcmPendingReload.set(side,name);return;}reloadSideFromTavern(side,name);}const isCompareEditable=t=>Boolean(t&&t.closest&&t.closest('.pcm-compare')&&(t.matches('textarea')||t.matches('input')||t.matches('select')));
/* 监听酒馆原生事件总线（eventSource/event_types 全局，不依赖酒馆助手）：预设变化时自动重载对应面板，
   实现「文件已改、前端跟着变」的实时同步——与案例.js 的 eventOn(tavern_events.*) 同源，这里是酒馆原生 API。
   有未导出修改的面板跳过自动同步，避免覆盖用户编辑。 */
function watchTavernPresetEvents(){const es=window.eventSource,et=window.event_types;if(!es||!et)return;try{es.on(et.PRESET_CHANGED,data=>{if(!data||(data.apiId&&data.apiId!=='openai'))return;const name=data.name;if(!name)return;for(const side of['old','new']){if(state.tavernSource[side]===name&&!state.dirty[side])requestSideReload(side,name);}});}catch(error){console.warn('[preset-compare-migrator] watch preset events failed',error);}}
function paintBackdrop(bd,rows,side){let i=0;const kids=bd.children;for(let r=0;r<rows.length;r++){const row=rows[r];if(side==='old'&&row.t==='+')continue;if(side==='new'&&row.t==='-')continue;let node=kids[i];if(!node){node=el('span');bd.append(node);node._k=null;}let key=row.t;for(let q=0;q<row.segs.length;q++){const s=row.segs[q];key+=''+s.t+''+s.text;}if(node._k!==key){node.className=row.t===' '?'ctx':row.t==='-'?'del':'add';const frag=document.createDocumentFragment();for(let q=0;q<row.segs.length;q++){const s=row.segs[q];if(side==='old'&&s.t==='+')continue;if(side==='new'&&s.t==='-')continue;if(s.t===' ')frag.append(document.createTextNode(s.text));else{const sp=el('span',s.t==='-'?'d':'a');sp.textContent=s.text;frag.append(sp);}}node.replaceChildren(frag);node._k=key;}i++;}while(kids.length>i)bd.lastChild.remove();}
function setupLiveDiff(detail){const areas=detail.querySelectorAll('.pcm-live-area');if(areas.length<2)return;const oldArea=areas[0],newArea=areas[1],oldBd=oldArea.previousElementSibling,newBd=newArea.previousElementSibling;if(!oldBd||!newBd)return;const align=(a,b)=>{const cs=getComputedStyle(a);b.style.fontFamily=cs.fontFamily;b.style.fontSize=cs.fontSize;b.style.lineHeight=cs.lineHeight;b.style.letterSpacing=cs.letterSpacing;b.style.paddingTop=(parseFloat(cs.paddingTop)+parseFloat(cs.borderTopWidth))+'px';b.style.paddingRight=(parseFloat(cs.paddingRight)+parseFloat(cs.borderRightWidth))+'px';b.style.paddingBottom=(parseFloat(cs.paddingBottom)+parseFloat(cs.borderBottomWidth))+'px';b.style.paddingLeft=(parseFloat(cs.paddingLeft)+parseFloat(cs.borderLeftWidth))+'px';};align(oldArea,oldBd);align(newArea,newBd);const update=()=>{const rows=buildRows(diffLines(oldArea.value,newArea.value));paintBackdrop(oldBd,rows,'old');paintBackdrop(newBd,rows,'new');};let timer=null;const deb=()=>{clearTimeout(timer);timer=setTimeout(update,250);};oldArea.addEventListener('input',deb);newArea.addEventListener('input',deb);const sync=(a,b)=>{b.scrollTop=a.scrollTop;b.scrollLeft=a.scrollLeft;};oldArea.addEventListener('scroll',()=>sync(oldArea,oldBd));newArea.addEventListener('scroll',()=>sync(newArea,newBd));if(window.requestIdleCallback)requestIdleCallback(update,{timeout:200});else setTimeout(update,0);}
const triggerOptions=[['','所有选项（默认）'],['normal','正常'],['continue','续写'],['impersonate','AI 帮答'],['swipe','备选回复'],['regenerate','重新生成'],['quiet','静默']];function triggerValue(prompt){return Array.isArray(prompt?.injection_trigger)&&prompt.injection_trigger.length?String(prompt.injection_trigger[0]||''):'';}
/* 跳转编辑区：触屏设备用即时定位（平滑滚动在移动端长页面会卡顿），桌面端保留平滑；rAF 确保 DOM 先完成布局再滚动。 */
function scrollToCompare(node){requestAnimationFrame(()=>{node.scrollIntoView({behavior:matchMedia('(hover: none)').matches?'auto':'smooth',block:'start'});});}
function renderCompare(){const detail=document.querySelector('[data-compare]');if(!detail)return;const oldPrompt=byId('old').get(state.activeId),newPrompt=byId('new').get(state.activeId),status=statusOf(state.activeId),current=(state.activeSide==='old'?oldPrompt:newPrompt)||oldPrompt||newPrompt;const wasHidden=detail.classList.contains('pcm-hidden'),dlg=detail.closest('.pcm-dialog'),dlgSt=wasHidden?null:(dlg?dlg.scrollTop:0),ownSt=wasHidden?null:detail.scrollTop;detail.replaceChildren();detail.classList.remove('pcm-hidden');const head=el('header','pcm-compare-head'),info=el('div');info.append(el('span','pcm-badge pcm-'+status,statusText[status]),el('h3','',current.name||'(未命名)'),el('code','',state.activeId));const actions=el('div','pcm-compare-actions');if(oldPrompt)actions.append(btn(newPrompt?'用旧版覆盖新版':'迁移到新版','migrate','pcm-primary','old'));if(newPrompt)actions.append(btn(oldPrompt?'用新版覆盖旧版':'迁移到旧版','migrate','pcm-primary','new'));const close=btn('×','collapse','pcm-collapse');close.title='收起对比';actions.append(close);head.append(info,actions);if(oldPrompt&&newPrompt)appendDiff(head);detail.append(head);const forms=el('div','pcm-version-forms');forms.append(versionEditor('old',oldPrompt),versionEditor('new',newPrompt));detail.append(forms);if(state.showDiff&&oldPrompt&&newPrompt)setupLiveDiff(detail);if(wasHidden)scrollToCompare(detail);else{if(dlg&&dlgSt!==null)dlg.scrollTop=dlgSt;if(ownSt!==null)detail.scrollTop=ownSt;}}
function renderFreeCompare(){const detail=document.querySelector('[data-compare]');if(!detail)return;const oldPrompt=byId('old').get(state.freeSelect.oldId),newPrompt=byId('new').get(state.freeSelect.newId);if(!oldPrompt||!newPrompt)return;const wasHidden=detail.classList.contains('pcm-hidden'),dlg=detail.closest('.pcm-dialog'),dlgSt=wasHidden?null:(dlg?dlg.scrollTop:0),ownSt=wasHidden?null:detail.scrollTop;detail.replaceChildren();detail.classList.remove('pcm-hidden');const head=el('header','pcm-compare-head'),info=el('div'),close=btn('×','collapse','pcm-collapse');info.append(el('span','pcm-badge pcm-changed','自由选择'),el('h3','',oldPrompt.name+' / '+newPrompt.name));close.title='收起对比';head.append(info,close);appendDiff(head);detail.append(head);const forms=el('div','pcm-version-forms');forms.append(versionEditor('old',oldPrompt),versionEditor('new',newPrompt));detail.append(forms);if(state.showDiff)setupLiveDiff(detail);if(wasHidden)scrollToCompare(detail);else{if(dlg&&dlgSt!==null)dlg.scrollTop=dlgSt;if(ownSt!==null)detail.scrollTop=ownSt;}}
function versionEditor(side,prompt){const wrap=el('section','pcm-version-editor');wrap.append(el('h4','',side==='old'?'旧版条目':'新版条目'));if(!prompt){wrap.append(el('div','pcm-missing','此版本没有该条目'));return wrap;}const form=el('form','pcm-inline-form');form.dataset.side=side;form.dataset.id=prompt.identifier;form.append(field('姓名','name',prompt.name),selectField('身份','role',prompt.role||'system',[['system','系统'],['user','用户'],['assistant','AI 助手']]),selectField('触发器','trigger',triggerValue(prompt),triggerOptions),selectField('位置','injection_position',prompt.injection_position??0,[['0','相对'],['1','聊天中']]));const chat=el('div','pcm-inline-chat');chat.append(field('深度','injection_depth',prompt.injection_depth??4,'number'),field('顺序','injection_order',prompt.injection_order??100,'number'));chat.hidden=prompt.injection_position!==1;form.append(chat);const pos=form.querySelector('[name=injection_position]');pos.addEventListener('change',()=>{chat.hidden=pos.value!=='1';});const contentLabel=el('label','pcm-inline-content');contentLabel.append(el('span','', '正文'));const editWrap=el('div','pcm-editwrap'+(state.showDiff?' live':'')),backdrop=el('pre','pcm-diff-backdrop'),area=el('textarea');backdrop.setAttribute('aria-hidden','true');area.name='content';area.className='pcm-live-area';area.value=prompt.content||'';editWrap.append(backdrop,area);contentLabel.append(editWrap);form.append(contentLabel);const save=btn('保存'+(side==='old'?'旧版':'新版')+'条目','save-inline','pcm-primary',side);save.type='submit';form.append(save);form.addEventListener('submit',saveInline);wrap.append(form);return wrap;}
/* 把内联表单写回数据模型并记一条撤回。 */
function applyInlineForm(form){const side=form.dataset.side,data=new FormData(form),prompt=byId(side).get(form.dataset.id);if(!prompt)return null;pushUndo({type:'edit',side,id:prompt.identifier,before:clone(prompt),modifiedBefore:[...state.modified[side]]});prompt.name=String(data.get('name')||'');prompt.role=String(data.get('role')||'system');prompt.injection_trigger=data.get('trigger')?[String(data.get('trigger'))]:[];prompt.injection_position=Number(data.get('injection_position'));if(prompt.injection_position===1){prompt.injection_depth=Number(data.get('injection_depth')||4);prompt.injection_order=Number(data.get('injection_order')||100);}prompt.content=String(data.get('content')||'');syncOrderEnabled(side,prompt.identifier,prompt.enabled!==false);state.modified[side].add(prompt.identifier);state.dirty[side]=true;rebuildCache();return{side,id:prompt.identifier};}
function saveInline(event){event.preventDefault();const r=applyInlineForm(event.currentTarget);if(!r)return;renderList('old');renderList('new');renderCompare();pcmToastr.success((r.side==='old'?'旧版':'新版')+'条目已保存');}
function updateSummary(side){const summary=document.querySelector('[data-summary="'+side+'"]'),preset=state[side];if(!summary||!preset)return;const counts={changed:0,removed:0,added:0,same:0};ordered(side).forEach(p=>counts[statusOf(p.identifier)]++);summary.textContent=preset.prompts.length+' 条 · 修改 '+counts.changed+' · '+(side==='old'?'新版删除 '+counts.removed:'新增 '+counts.added)+(state.dirty[side]?' · 有未导出修改':'');}
function valueBox(title,value,large){const box=el('div','pcm-value');box.append(el('small','',title));if(large){const area=el('textarea');area.readOnly=true;area.value=valueText(value);box.append(area);}else box.append(el('pre','',valueText(value)));return box;}
function selectField(labelText,name,value,options){const label=el('label','pcm-control');label.append(el('span','',labelText));const select=el('select');select.name=name;for(const optionData of options){const option=el('option','',optionData[1]);option.value=optionData[0];option.selected=String(value)===String(optionData[0]);select.append(option);}label.append(select);return label;}
function editor(side,prompt){const form=el('form','pcm-editor');form.dataset.side=side;form.dataset.id=prompt.identifier;form.append(el('h3','', '编辑'+(side==='old'?'旧版':'新版')+'条目'));form.append(field('姓名','name',prompt.name),selectField('身份','role',prompt.role||'system',[['system','系统'],['user','用户'],['assistant','AI 助手']]),field('启用','enabled',prompt.enabled,'checkbox'));const triggerValue=Array.isArray(prompt.injection_trigger)&&prompt.injection_trigger.length?'all-explicit':'default';form.append(selectField('触发器','trigger_mode',triggerValue,[['default','所有类型（默认）'],['all-explicit','所有类型（明确指定）']]));form.append(selectField('位置','injection_position',prompt.injection_position??0,[['0','提示词管理器'],['1','聊天中']]));const chatFields=el('div','pcm-chat-fields');chatFields.dataset.chatFields='';chatFields.append(field('深度','injection_depth',prompt.injection_depth??4,'number'),field('顺序','injection_order',prompt.injection_order??100,'number'));if(prompt.injection_position!==1)chatFields.hidden=true;form.append(chatFields);const position=form.querySelector('[name=injection_position]');position.addEventListener('change',()=>{chatFields.hidden=position.value!=='1';});const contentLabel=el('label','pcm-editor-content');contentLabel.append(el('span','', '正文'));const content=el('textarea');content.name='content';content.value=prompt.content||'';contentLabel.append(content);form.append(contentLabel);const json=el('details','pcm-json');json.append(el('summary','', '完整条目 JSON'));const area=el('textarea');area.name='full_json';area.value=JSON.stringify(prompt,null,2);json.append(area);form.append(json);const save=btn('保存修改','save','pcm-primary',side);save.type='submit';form.append(save);form.addEventListener('submit',saveEdit);return form;}
function field(labelText,name,value,type='text'){const label=el('label','pcm-control');label.append(el('span','',labelText));const input=el('input');input.name=name;input.type=type;if(type==='checkbox')input.checked=value!==false;else input.value=value??'';label.append(input);return label;}
function saveEdit(event){event.preventDefault();const form=event.currentTarget,side=form.dataset.side,data=new FormData(form);try{let prompt=JSON.parse(String(data.get('full_json')));if(!prompt||typeof prompt!=='object'||Array.isArray(prompt))throw new Error('完整 JSON 必须是对象');prompt.identifier=form.dataset.id;prompt.name=String(data.get('name')||'');prompt.role=String(data.get('role')||'system');prompt.enabled=data.get('enabled')==='on';prompt.content=String(data.get('content')||'');prompt.injection_position=Number(data.get('injection_position'));prompt.injection_trigger=data.get('trigger_mode')==='all-explicit'?['normal','continue','impersonate','swipe','regenerate','quiet']:[];if(prompt.injection_position===1){prompt.injection_depth=Number(data.get('injection_depth')||4);prompt.injection_order=Number(data.get('injection_order')||100);}const previous=byId(side).get(prompt.identifier);pushUndo({type:'edit',side,id:prompt.identifier,before:clone(previous),modifiedBefore:[...state.modified[side]]});const index=state[side].prompts.findIndex(p=>p.identifier===prompt.identifier);state[side].prompts[index]=prompt;syncOrderEnabled(side,prompt.identifier,prompt.enabled);state.modified[side].add(prompt.identifier);state.dirty[side]=true;rebuildCache();renderList('old');renderList('new');renderCompare();pcmToastr.success('条目已保存');}catch(e){pcmToastr.error(e.message,'保存失败');}}
function orderArray(preset){let entry=promptOrderEntry(preset);if(!entry){entry={character_id:100001,order:[]};if(!Array.isArray(preset.prompt_order))preset.prompt_order=[];preset.prompt_order.push(entry);}return entry.order||(entry.order=[]);}
function syncOrderEnabled(side,id,enabled){const item=orderArray(state[side]).find(x=>x.identifier===id);if(item)item.enabled=enabled;else orderArray(state[side]).push({identifier:id,enabled});}
function migrate(sourceSide){const targetSide=sourceSide==='old'?'new':'old',source=state[sourceSide],target=state[targetSide],prompt=byId(sourceSide).get(state.activeId);if(!source||!target||!prompt){pcmToastr.error('请先导入两份预设');return;}const existing=target.prompts.findIndex(p=>p.identifier===prompt.identifier);if(existing>=0&&!confirm('目标预设已有同 ID 条目，确定覆盖吗？'))return;if(existing>=0){target.prompts[existing]=clone(prompt);syncOrderEnabled(targetSide,prompt.identifier,prompt.enabled!==false);}else{const sourceIds=ordered(sourceSide).map(p=>p.identifier),targetIds=ordered(targetSide).map(p=>p.identifier),sourceIndex=sourceIds.indexOf(prompt.identifier);let beforeId=null,afterId=null;for(let i=sourceIndex-1;i>=0;i--)if(targetIds.includes(sourceIds[i])){beforeId=sourceIds[i];break;}if(!beforeId)for(let i=sourceIndex+1;i<sourceIds.length;i++)if(targetIds.includes(sourceIds[i])){afterId=sourceIds[i];break;}let promptIndex=target.prompts.length;if(beforeId){const i=target.prompts.findIndex(p=>p.identifier===beforeId);promptIndex=i+1;}else if(afterId){const i=target.prompts.findIndex(p=>p.identifier===afterId);promptIndex=i;}target.prompts.splice(Math.max(0,promptIndex),0,clone(prompt));const order=orderArray(target),oldOrderIndex=order.findIndex(x=>x.identifier===prompt.identifier);if(oldOrderIndex>=0)order.splice(oldOrderIndex,1);let orderIndex=order.length;if(beforeId){const i=order.findIndex(x=>x.identifier===beforeId);orderIndex=i+1;}else if(afterId){const i=order.findIndex(x=>x.identifier===afterId);orderIndex=i;}order.splice(Math.max(0,orderIndex),0,{identifier:prompt.identifier,enabled:prompt.enabled!==false});}state.dirty[targetSide]=true;renderAll();pcmToastr.success('条目已迁移到'+(targetSide==='old'?'旧版':'新版')+'的对应位置');}
function exportPreset(side){const preset=state[side];if(!preset)return;const blob=new Blob([JSON.stringify(preset,null,2)],{type:'application/json;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=(state[side+'Name']||side+'-preset').replace(/\.json$/i,'')+'-已编辑.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);state.dirty[side]=false;renderList(side);}
function updateStatusFor(id){const o=byId('old').get(id),n=byId('new').get(id);state.cache.status.set(id,o&&!n?'removed':!o&&n?'added':o&&n&&!equal(withoutEnabled(o),withoutEnabled(n))?'changed':'same');}
function rowById(list,id){if(!list)return null;return[...list.querySelectorAll('.pcm-row')].find(row=>row.dataset.dragId===id)||null;}
function updateRowOperationTags(row,side,id){if(!row)return;let tags=row.querySelector('.pcm-operation-tags');if(!tags){tags=el('span','pcm-operation-tags');row.querySelector('.pcm-row-title')?.append(tags);}tags.querySelectorAll('.pcm-op-tag').forEach(t=>t.remove());if(state.dragged[side].has(id))tags.append(el('span','pcm-op-tag pcm-op-dragged','已拖拽'));if(state.modified[side].has(id))tags.append(el('span','pcm-op-tag pcm-op-modified','已修改'));}
function updateRowBadge(row,id,side){if(!row)return;const status=statusOf(id),badge=row.querySelector('.pcm-badge');if(badge){badge.className='pcm-badge pcm-'+status;badge.textContent=badgeText(id,side);}}
function getBaiBaiGroupState(preset){const value=preset?.extensions?.baibaiToolkit?.presetPromptGroups;return value&&typeof value==='object'?value:null;}function ensureBaiBaiGroupState(preset){preset.extensions=preset.extensions&&typeof preset.extensions==='object'?preset.extensions:{};preset.extensions.baibaiToolkit=preset.extensions.baibaiToolkit&&typeof preset.extensions.baibaiToolkit==='object'?preset.extensions.baibaiToolkit:{};let value=preset.extensions.baibaiToolkit.presetPromptGroups;if(!value||typeof value!=='object')value=preset.extensions.baibaiToolkit.presetPromptGroups={groups:[],prompts:{}};if(!Array.isArray(value.groups))value.groups=[];if(!value.prompts||typeof value.prompts!=='object')value.prompts={};return value;}function syncBaiBaiGroupAfterMove(sourceSide,targetSide,id,beforeId){if(sourceSide===targetSide)return;const sourceGroup=getBaiBaiGroupState(state[sourceSide]),targetGroup=getBaiBaiGroupState(state[targetSide]);if(!sourceGroup&&!targetGroup)return;const groupState=ensureBaiBaiGroupState(state[targetSide]),orderedIds=state.cache.ordered[targetSide].map(p=>p.identifier),index=beforeId?orderedIds.indexOf(beforeId):orderedIds.length,nextId=index>=0&&index<orderedIds.length?orderedIds[index]:null,prevId=index>0?orderedIds[index-1]:null;const nextGroup=nextId?groupState.prompts?.[nextId]?.groupId:null,prevGroup=prevId?groupState.prompts?.[prevId]?.groupId:null,sourceId=sourceGroup?.prompts?.[id]?.groupId,validGroups=new Set((groupState.groups||[]).map(g=>String(g.id)));const candidate=[nextGroup,prevGroup,sourceId].find(groupId=>groupId&&validGroups.has(String(groupId)));if(candidate)groupState.prompts[id]={groupId:String(candidate)};else delete groupState.prompts[id];}
function movePrompt(sourceSide,targetSide,id,beforeId){const source=state[sourceSide],target=state[targetSide],prompt=byId(sourceSide).get(id);if(target){pushUndo({type:'move',side:targetSide,promptOrder:target.prompts.map(p=>p.identifier),prompts:new Map(target.prompts.map(p=>[p.identifier,p])),promptOrderData:clone(target.prompt_order),extensionsBefore:clone(target.extensions),draggedBefore:[...state.dragged[targetSide]]});}if(!source||!target||!prompt)return;const targetOrdered=state.cache.ordered[targetSide];const existing=targetOrdered.findIndex(p=>p.identifier===id);let index=beforeId?targetOrdered.findIndex(p=>p.identifier===beforeId):targetOrdered.length;if(existing>=0){if(index>existing)index--;targetOrdered.splice(existing,1);}if(index<0||index>targetOrdered.length)index=targetOrdered.length;const copy=sourceSide===targetSide?prompt:clone(prompt);targetOrdered.splice(index,0,copy);target.prompts=targetOrdered.slice();state.cache.maps[targetSide].set(id,copy);const rawOrder=orderArray(target),entryHost=promptOrderEntry(target),xidOf=x=>typeof x==='string'?x:x?.identifier,clean=rawOrder.filter(x=>xidOf(x)!==id);let oi=beforeId?clean.findIndex(x=>xidOf(x)===beforeId):clean.length;if(oi<0&&beforeId===id){const self=rawOrder.findIndex(x=>xidOf(x)===id);if(self>=0)oi=self;}if(oi<0)oi=clean.length;clean.splice(oi,0,{identifier:id,enabled:copy.enabled!==false});(entryHost||target.prompt_order[0]).order=clean;syncBaiBaiGroupAfterMove(sourceSide,targetSide,id,beforeId);updateStatusFor(id);if(sourceSide!==targetSide)state.dragged[targetSide].add(id);state.dirty[targetSide]=true;state.activeId=null;state.activeSide=null;hideCompare();rebuildCache();renderList(sourceSide);if(targetSide!==sourceSide)renderList(targetSide);pcmToastr.success('条目已放置到目标位置');}
let outerScrollTouch=null;function isOuterScrollSurface(target){if(!target||typeof target.closest!=='function')return false;if(target.closest('button,input,select,textarea,label,a,.pcm-row,.pcm-group'))return false;return Boolean(target.closest('.pcm-dialog,.pcm-app,.pcm-header,.pcm-lists,.pcm-pane,.pcm-pane-head,.pcm-tools,.pcm-summary,.pcm-list'));}function onOuterScrollTouchStart(event){if(!isOuterScrollSurface(event.target)||event.touches.length!==1)return;const point=event.touches[0],dialog=document.getElementById(APP_ID+'-dialog');outerScrollTouch={dialog,lastY:point.clientY,startY:point.clientY,moved:false};}function onOuterScrollTouchMove(event){if(!outerScrollTouch||event.touches.length!==1)return;const point=event.touches[0],delta=outerScrollTouch.lastY-point.clientY;if(!outerScrollTouch.moved&&Math.abs(point.clientY-outerScrollTouch.startY)<4)return;outerScrollTouch.moved=true;outerScrollTouch.lastY=point.clientY;event.preventDefault();event.stopPropagation();outerScrollTouch.dialog.scrollTop+=delta;}function onOuterScrollTouchEnd(){outerScrollTouch=null;}
let touchDrag=null,touchContacts=0;
/* 拖拽自动滚动（Windows 文件管理器风格，触屏长按/桌面HTML5拖拽共用一套 rAF 循环）：指针进入某列表上/下边缘区并连续停留
   AUTOSCROLL_DWELL_MS 毫秒后才持续滚动该列表（快速划过/跨面板水平移动经过边缘不足该时长，不会误触发），越靠近边缘越快、
   激活后 250ms 内渐进加速不猛冲、滚到边界自停、松手/离边即停。停留计时按「哪个列表+上/下边缘」区分，划出该区自动重置。 */
let dragAutoScrollRaf=0,html5DragPointer=null,edgeKey='',edgeSince=0;
const AUTOSCROLL_DWELL_MS=450,AUTOSCROLL_MAX_STEP=10,AUTOSCROLL_ZONE=64,AUTOSCROLL_SLACK=4;
function startDragAutoScroll(){if(dragAutoScrollRaf)return;edgeKey='';edgeSince=0;const tick=()=>{dragAutoScrollStep();dragAutoScrollRaf=requestAnimationFrame(tick);};dragAutoScrollRaf=requestAnimationFrame(tick);}
function stopDragAutoScroll(){if(dragAutoScrollRaf){cancelAnimationFrame(dragAutoScrollRaf);dragAutoScrollRaf=0;}html5DragPointer=null;edgeKey='';edgeSince=0;}
function dragAutoScrollStep(){const now=performance.now();let x,y,holdingDrag=null;if(touchDrag&&touchDrag.holding&&touchDrag.my!==undefined){x=touchDrag.mx;y=touchDrag.my;holdingDrag=touchDrag;}else if(pointerDrag&&pointerDrag.holding&&pointerDrag.my!==undefined){x=pointerDrag.mx;y=pointerDrag.my;holdingDrag=pointerDrag;}else if(html5DragPointer){if(html5DragPointer.t===undefined||now-html5DragPointer.t>500)return;x=html5DragPointer.x;y=html5DragPointer.y;}else return;const e=dragAutoScrollEdge(x,y),key=e?(e.list.dataset.list+':'+e.dir):'';if(key!==edgeKey){edgeKey=key;edgeSince=now;}if(!e)return;const dwell=now-edgeSince;if(dwell<AUTOSCROLL_DWELL_MS)return;const ramp=Math.min(1,(dwell-AUTOSCROLL_DWELL_MS)/250),before=e.list.scrollTop;e.list.scrollTop=before+Math.ceil(e.delta*Math.max(ramp,0.34));if(e.list.scrollTop!==before&&holdingDrag)processDragAt(holdingDrag);}
function dragAutoScrollEdge(x,y){for(const list of document.querySelectorAll('.pcm-list')){const r=list.getBoundingClientRect();if(x<r.left||x>r.right)continue;if(y<r.top-AUTOSCROLL_SLACK||y>r.bottom+AUTOSCROLL_SLACK)continue;const zone=Math.min(AUTOSCROLL_ZONE,Math.max(36,r.height*0.22));if(y<r.top+zone)return{list,dir:'up',delta:-Math.max(2,Math.ceil((r.top+zone-y)/zone*AUTOSCROLL_MAX_STEP))};if(y>r.bottom-zone)return{list,dir:'down',delta:Math.max(2,Math.ceil((y-(r.bottom-zone))/zone*AUTOSCROLL_MAX_STEP))};}return null;}function onTouchContactChange(event){touchContacts=event.touches.length;}
function touchById(event,id){for(const t of event.touches)if(t.identifier===id)return t;return null;}function touchEnded(event,id){for(const t of event.changedTouches)if(t.identifier===id)return true;return false;}function cleanupTouchDrag(){if(!touchDrag)return;clearTimeout(touchDrag.timer);if(touchDrag.raf)cancelAnimationFrame(touchDrag.raf);const wasHolding=touchDrag.holding;touchDrag.row.classList.remove('pcm-dragging');touchDrag.dialog?.classList.remove('pcm-touch-dragging');clearDropMarker();stopDragAutoScroll();touchDrag=null;if(wasHolding)pcmUnlock();}function onTouchStart(event){const row=event.target.closest('.pcm-row');if(!row)return;if(touchDrag||event.touches.length!==1)return;const point=event.touches[0],dialog=row.closest('.pcm-dialog');touchDrag={id:point.identifier,row,dialog,timer:setTimeout(()=>{if(!touchDrag)return;touchDrag.holding=true;row.classList.add('pcm-dragging');dialog?.classList.add('pcm-touch-dragging');pcmLock();startDragAutoScroll();touchDrag.scrollHome={};document.querySelectorAll('.pcm-list').forEach(l=>{touchDrag.scrollHome[l.dataset.list]=l.scrollTop;});},450),x:point.clientX,y:point.clientY,holding:false,targetSide:null,beforeId:null,targetGroupId:null};}function onTouchMove(event){if(!touchDrag)return;const point=touchById(event,touchDrag.id);if(!point)return;if(!touchDrag.holding){if(Math.abs(point.clientX-touchDrag.x)>8||Math.abs(point.clientY-touchDrag.y)>8){clearTimeout(touchDrag.timer);touchDrag=null;}return;}event.preventDefault();touchDrag.mx=point.clientX;touchDrag.my=point.clientY;if(!touchDrag.raf)touchDrag.raf=requestAnimationFrame(()=>{if(touchDrag)touchDrag.raf=null;processTouchDrag();});}function processTouchDrag(){processDragAt(touchDrag);}function processPointerDrag(){processDragAt(pointerDrag);}function nearestRowTo(list,y,excludeRow){let best=null,bestD=Infinity;for(const r of list.querySelectorAll('.pcm-row')){if(r===excludeRow)continue;const rect=r.getBoundingClientRect();if(rect.height===0)continue;const d=y<rect.top?rect.top-y:(y>rect.bottom?y-rect.bottom:0);if(d<bestD){bestD=d;best=r;}}return best;}
function processDragAt(drag){if(!drag||!drag.holding||drag.mx===undefined||drag.my===undefined)return;drag.groupAssign=false;
  /* Dead zone: long-press released nearly in place clears the drop target so nothing moves. */
  if(Math.abs(drag.my-drag.y)<12&&Math.abs(drag.mx-drag.x)<12){clearDropMarker();drag.beforeId=null;drag.targetSide=null;drag.targetGroupId=null;return;}
  drag.suppressClick=true;
  const hit=document.elementFromPoint(drag.mx,drag.my),list=hit?.closest('.pcm-list'),row=hit?.closest('.pcm-row');if(!list){clearDropMarker();drag.beforeId=null;drag.targetSide=null;drag.targetGroupId=null;return;}if(row&&row!==drag.row){drag.beforeId=markDropTarget(row,{clientY:drag.my});if(drag.beforeId===drag.row.dataset.dragId)drag.beforeId=nextRenderedRowId(drag.row);drag.targetSide=list.dataset.list;drag.targetGroupId=groupIdForRow(row);}else if(!row){const group=hit.closest('.pcm-group:not(.pcm-uninjected)');if(group){const rows=group.querySelectorAll('.pcm-group-body .pcm-row'),lastRow=rows[rows.length-1];clearDropMarker();group.classList.add('pcm-group-drop');dropEndList=group;drag.beforeId=lastRow?nextRenderedRowId(lastRow):nextRenderedRowId(group);if(drag.beforeId===drag.row.dataset.dragId)drag.beforeId=nextRenderedRowId(drag.row);drag.targetSide=list.dataset.list;drag.targetGroupId=group.dataset.groupId||null;drag.groupAssign=!!(group.dataset.groupId&&!lastRow);}else{const near=nearestRowTo(list,drag.my,drag.row);if(near){drag.beforeId=markDropTarget(near,{clientY:drag.my});if(drag.beforeId===drag.row.dataset.dragId)drag.beforeId=nextRenderedRowId(drag.row);drag.targetSide=list.dataset.list;drag.targetGroupId=groupIdForRow(near);}else{clearDropMarker();list.classList.add('pcm-drop-end');dropEndList=list;drag.beforeId=null;drag.targetSide=list.dataset.list;drag.targetGroupId=null;}}}else{clearDropMarker();drag.beforeId=null;drag.targetSide=null;drag.targetGroupId=null;}}function onTouchEnd(event){if(!touchDrag)return;if(!touchEnded(event,touchDrag.id))return;clearTimeout(touchDrag.timer);if(touchDrag.raf)cancelAnimationFrame(touchDrag.raf);if(touchDrag.holding){for(const t of event.changedTouches)if(t.identifier===touchDrag.id){touchDrag.mx=t.clientX;touchDrag.my=t.clientY;break;}try{processTouchDrag();}catch(_){}}const drag=touchDrag;touchDrag=null;drag.row.classList.remove('pcm-dragging');const jitter=drag.mx===undefined||drag.my===undefined||(Math.abs(drag.my-drag.y)<12&&Math.abs(drag.mx-drag.x)<12);try{if(drag.holding&&drag.targetSide&&!jitter){event.preventDefault();const srcSide=drag.row.dataset.dragSide;if(drag.groupAssign)assignPromptToGroup(srcSide,drag.targetSide,drag.row.dataset.dragId,drag.targetGroupId);else{movePrompt(srcSide,drag.targetSide,drag.row.dataset.dragId,drag.beforeId);applyDropGroup(drag.targetSide,drag.row.dataset.dragId,drag.targetGroupId);rebuildCache();renderList(drag.targetSide);}if(srcSide!==drag.targetSide&&drag.scrollHome){const srcList=document.querySelector('[data-list="'+srcSide+'"]');if(srcList&&drag.scrollHome[srcSide]!==undefined)srcList.scrollTop=drag.scrollHome[srcSide];}}}catch(error){console.error('[preset-compare-migrator] touch drop failed',error);}clearDropMarker();stopDragAutoScroll();drag.dialog?.classList.remove('pcm-touch-dragging');if(drag.holding)pcmUnlock();}function onTouchCancel(event){if(!touchDrag||!touchEnded(event,touchDrag.id))return;cleanupTouchDrag();}
/* 指针长按拖拽（桌面/混合设备）：触屏长按由 onTouchStart 系处理，这里只接管非 touch 指针（鼠标/触控笔），
   解决 TauriTavern/Windows 端 HTML5 拖拽（dragstart）不触发、条目无法长按拖动的问题。
   按住 320ms 进入拖拽（holding），之后复用 processDragAt 的命中/落点逻辑；未达长按的移动/抬起不拦截，点击展开不受影响。 */
let pointerDrag=null,suppressClickUntil=0;
function cleanupPointerDrag(){if(!pointerDrag)return;clearTimeout(pointerDrag.timer);if(pointerDrag.raf)cancelAnimationFrame(pointerDrag.raf);const wasHolding=pointerDrag.holding;pointerDrag.row.classList.remove('pcm-dragging');pointerDrag.dialog?.classList.remove('pcm-touch-dragging');clearDropMarker();stopDragAutoScroll();pointerDrag=null;if(wasHolding)pcmUnlock();}
function beginPointerHold(){if(!pointerDrag||pointerDrag.holding)return;pointerDrag.holding=true;pointerDrag.row.classList.add('pcm-dragging');pointerDrag.dialog?.classList.add('pcm-touch-dragging');pcmLock();startDragAutoScroll();pointerDrag.scrollHome={};document.querySelectorAll('.pcm-list').forEach(l=>{pointerDrag.scrollHome[l.dataset.list]=l.scrollTop;});}function onRowPointerDown(event){if(event.pointerType==='touch')return;if(touchDrag)return;if(event.button!==undefined&&event.button!==0)return;if(pointerDrag)cleanupPointerDrag();const row=event.target.closest?.('.pcm-row');if(!row)return;const dialog=row.closest('.pcm-dialog');pointerDrag={id:event.pointerId,row,dialog,timer:setTimeout(beginPointerHold,320),x:event.clientX,y:event.clientY,holding:false};}
function onRowPointerMove(event){if(!pointerDrag||event.pointerId!==pointerDrag.id)return;if(!pointerDrag.holding){if(Math.abs(event.clientX-pointerDrag.x)>4||Math.abs(event.clientY-pointerDrag.y)>4){pointerDrag.mx=event.clientX;pointerDrag.my=event.clientY;beginPointerHold();}return;}event.preventDefault();pointerDrag.mx=event.clientX;pointerDrag.my=event.clientY;if(!pointerDrag.raf)pointerDrag.raf=requestAnimationFrame(()=>{if(pointerDrag)pointerDrag.raf=null;processPointerDrag();});}
function onRowPointerUp(event){if(!pointerDrag||event.pointerId!==pointerDrag.id)return;clearTimeout(pointerDrag.timer);if(pointerDrag.raf)cancelAnimationFrame(pointerDrag.raf);if(pointerDrag.holding){pointerDrag.mx=event.clientX;pointerDrag.my=event.clientY;try{processPointerDrag();}catch(_){}}const drag=pointerDrag;pointerDrag=null;if(drag.holding&&drag.suppressClick)suppressClickUntil=performance.now()+400;drag.row.classList.remove('pcm-dragging');const jitter=drag.mx===undefined||drag.my===undefined||(Math.abs(drag.my-drag.y)<12&&Math.abs(drag.mx-drag.x)<12);try{if(drag.holding&&drag.targetSide&&!jitter){const srcSide=drag.row.dataset.dragSide;if(drag.groupAssign)assignPromptToGroup(srcSide,drag.targetSide,drag.row.dataset.dragId,drag.targetGroupId);else{movePrompt(srcSide,drag.targetSide,drag.row.dataset.dragId,drag.beforeId);applyDropGroup(drag.targetSide,drag.row.dataset.dragId,drag.targetGroupId);rebuildCache();renderList(drag.targetSide);}if(srcSide!==drag.targetSide&&drag.scrollHome){const srcList=document.querySelector('[data-list="'+srcSide+'"]');if(srcList&&drag.scrollHome[srcSide]!==undefined)srcList.scrollTop=drag.scrollHome[srcSide];}}}catch(error){console.error('[preset-compare-migrator] pointer drop failed',error);}clearDropMarker();stopDragAutoScroll();drag.dialog?.classList.remove('pcm-touch-dragging');if(drag.holding)pcmUnlock();}
function onRowPointerCancel(event){if(!pointerDrag||event.pointerId!==pointerDrag.id)return;cleanupPointerDrag();}
let dropMarker=null,dropClass='',dropEndList=null;function clearDropMarker(){if(dropMarker&&dropClass)dropMarker.classList.remove(dropClass);if(dropEndList){dropEndList.classList.remove('pcm-drop-end');dropEndList.classList.remove('pcm-group-drop');}dropMarker=null;dropClass='';dropEndList=null;}function nextRenderedRowId(row){const direct=row.nextElementSibling;if(direct?.matches('.pcm-row'))return direct.dataset.dragId;let sibling=row.closest('.pcm-group')?.nextElementSibling||direct;while(sibling){if(sibling.matches?.('.pcm-row'))return sibling.dataset.dragId;const nested=sibling.querySelector?.('.pcm-row');if(nested)return nested.dataset.dragId;sibling=sibling.nextElementSibling;}return null;}function markDropTarget(row,event){const rect=row.getBoundingClientRect(),after=event.clientY>rect.top+rect.height/2,nextClass=after?'pcm-drop-after':'pcm-drop-before';if(dropMarker!==row||dropClass!==nextClass){clearDropMarker();row.classList.add(nextClass);dropMarker=row;dropClass=nextClass;}return after?nextRenderedRowId(row):row.dataset.dragId;}function onDragStart(event){if(touchContacts>0||pointerDrag){if(pointerDrag)cleanupPointerDrag();event.preventDefault();return;}const row=event.target.closest('.pcm-row');if(!row)return;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',JSON.stringify({id:row.dataset.dragId,side:row.dataset.dragSide}));row.classList.add('pcm-dragging');pcmLock();html5DragLock=true;startDragAutoScroll();}function groupIdForRow(row){const group=row?.closest('.pcm-group');return group?.dataset.groupId||null;}
function applyDropGroup(side,id,groupId){const groupState=getBaiBaiGroupState(state[side]);if(!groupState&&!groupId)return;const ensured=ensureBaiBaiGroupState(state[side]);if(groupId)ensured.prompts[id]={groupId:String(groupId)};else delete ensured.prompts[id];}
function onDragOver(event){html5DragPointer={x:event.clientX,y:event.clientY,t:performance.now()};const list=event.target.closest('.pcm-list');if(!list)return;event.preventDefault();const row=event.target.closest('.pcm-row');if(row){markDropTarget(row,event);return;}const groupHead=event.target.closest('.pcm-group-head'),group=groupHead?.closest('.pcm-group');if(group?.dataset.groupId){clearDropMarker();group.classList.add('pcm-group-drop');dropEndList=group;return;}if(dropEndList!==list){clearDropMarker();list.classList.add('pcm-drop-end');dropEndList=list;}}function onDrop(event){stopDragAutoScroll();const list=event.target.closest('.pcm-list');if(!list)return;event.preventDefault();const row=event.target.closest('.pcm-row');if(row){try{const data=JSON.parse(event.dataTransfer.getData('text/plain')),beforeId=markDropTarget(row,event),targetSide=list.dataset.list,targetGroupId=groupIdForRow(row);clearDropMarker();movePrompt(data.side,targetSide,data.id,beforeId);applyDropGroup(targetSide,data.id,targetGroupId);rebuildCache();renderList(targetSide);}catch{clearDropMarker();}return;}const groupHead=event.target.closest('.pcm-group-head'),group=groupHead?.closest('.pcm-group');if(group?.dataset.groupId){try{const data=JSON.parse(event.dataTransfer.getData('text/plain'));group.classList.remove('pcm-group-drop');assignPromptToGroup(data.side,group.dataset.groupSide,data.id,group.dataset.groupId);}catch{}clearDropMarker();return;}try{const data=JSON.parse(event.dataTransfer.getData('text/plain'));clearDropMarker();movePrompt(data.side,list.dataset.list,data.id,null);}catch{clearDropMarker();}}
function onDragEnd(event){if(event.target instanceof Element)event.target.closest('.pcm-row')?.classList.remove('pcm-dragging');clearDropMarker();stopDragAutoScroll();if(html5DragLock){html5DragLock=false;pcmUnlock();}}
async function tavernPresetCandidates(){const candidates=new Map(),add=(name,value)=>{if(value&&Array.isArray(value.prompts))candidates.set(String(name||'未命名预设'),value);};try{const module=await import('/scripts/openai.js'),names=module.openai_setting_names||{},settings=module.openai_settings||[];if(Array.isArray(names))names.forEach((name,index)=>add(name,settings[index]));else Object.entries(names).forEach(([name,index])=>add(name,settings[Number(index)]));}catch(error){console.warn('[preset-compare-migrator] Failed to import openai preset module',error);}return candidates;}
async function pullTavernPreset(){const candidates=await tavernPresetCandidates();if(!candidates.size){pcmToastr.warning('未能读取 Chat Completion/OpenAI 预设。','未找到酒馆预设');return;}tavernPresetPickerData=candidates;let picker=document.querySelector('[data-tavern-picker]');if(!picker){picker=el('section','pcm-picker');picker.dataset.tavernPicker='';const panel=el('div','pcm-picker-panel'),head=el('header','pcm-picker-head');head.append(el('h3','', '选择酒馆预设'),btn('×','close-picker','pcm-collapse'));panel.append(head);const list=el('div','pcm-picker-list');list.dataset.pickerList='';panel.append(list);picker.append(panel);document.getElementById(APP_ID+'-dialog').append(picker);}const list=picker.querySelector('[data-picker-list]');list.replaceChildren();for(const [name,preset] of candidates){const item=btn(name,'choose-tavern','pcm-picker-item');item.dataset.presetName=name;item.append(el('small','',preset.prompts.length+' 个条目'));list.append(item);}picker.classList.add('open');}
function chooseTavernPreset(name){const preset=tavernPresetPickerData.get(name);if(!preset)return;state.old=validate(clone(preset));state.oldName=name+'.json';state.tavernSource.old=name;state.dirty.old=false;state.activeId=null;document.querySelector('[data-tavern-picker]')?.classList.remove('open');hideCompare();rebuildCache();renderAll(false);pcmToastr.success('已从酒馆载入：'+name);}
function snapshotGroupChange(side){const preset=state[side];pushUndo({type:'move',side,promptOrder:preset.prompts.map(p=>p.identifier),prompts:new Map(preset.prompts.map(p=>[p.identifier,p])),promptOrderData:clone(preset.prompt_order),extensionsBefore:clone(preset.extensions),draggedBefore:[...state.dragged[side]]});}
function deletePrompt(side,id){const preset=state[side];if(!preset)return;if(!confirm('确定从'+(side==='old'?'旧版':'新版')+'删除该条目吗？（可撤回）'))return;snapshotGroupChange(side);preset.prompts=preset.prompts.filter(p=>p.identifier!==id);const order=orderArray(preset),oi=order.findIndex(x=>(typeof x==='string'?x:x?.identifier)===id);if(oi>=0)order.splice(oi,1);if(state.activeId===id){state.activeId=null;state.activeSide=null;hideCompare();}state.dirty[side]=true;rebuildCache();renderAll();pcmToastr.success('已删除条目');}
function duplicatePrompt(side,id){const preset=state[side],prompt=byId(side).get(id);if(!preset||!prompt)return;snapshotGroupChange(side);const copy=clone(prompt);copy.identifier=crypto.randomUUID();copy.name=(prompt.name||'(未命名)')+' 副本';const idx=preset.prompts.findIndex(p=>p.identifier===id);preset.prompts.splice(idx<0?preset.prompts.length:idx+1,0,copy);const order=orderArray(preset),oi=order.findIndex(x=>(typeof x==='string'?x:x?.identifier)===id);order.splice(oi<0?order.length:oi+1,0,{identifier:copy.identifier,enabled:prompt.enabled!==false});const srcGroups=getBaiBaiGroupState(preset),srcGid=srcGroups?.prompts?.[id]?.groupId;if(srcGid&&Array.isArray(srcGroups.groups)&&srcGroups.groups.some(g=>String(g.id)===String(srcGid)))ensureBaiBaiGroupState(preset).prompts[copy.identifier]={groupId:String(srcGid)};state.dirty[side]=true;rebuildCache();renderAll();pcmToastr.success('已复制条目');}
function newGroup(side){const preset=state[side];if(!preset)return;const name=prompt('输入分组名称','新分组');if(!name)return;snapshotGroupChange(side);const groupState=ensureBaiBaiGroupState(preset);const groupId=crypto.randomUUID();groupState.groups.push({id:groupId,name,order:groupState.groups.length,collapsed:false,enabled:true});state.grouping={side,groupId};state.dirty[side]=true;renderList(side);}
function renameGroup(side,id){const groupState=getBaiBaiGroupState(state[side]),group=groupState?.groups?.find(g=>String(g.id)===String(id));if(!group)return;const name=prompt('输入新的分组名称',group.name||'');if(!name)return;snapshotGroupChange(side);group.name=name;state.dirty[side]=true;renderList(side);}
function deleteGroup(side,id){const groupState=getBaiBaiGroupState(state[side]);if(!groupState||!confirm('删除分组？组内条目会变为未分组，不会被删除。'))return;snapshotGroupChange(side);groupState.groups=groupState.groups.filter(g=>String(g.id)!==String(id));for(const [promptId,meta] of Object.entries(groupState.prompts||{}))if(String(meta?.groupId)===String(id))delete groupState.prompts[promptId];state.dirty[side]=true;renderList(side);}
function assignPromptToGroup(sourceSide,targetSide,id,groupId){const source=state[sourceSide],target=state[targetSide],prompt=byId(sourceSide).get(id);if(!source||!target||!prompt)return;const groupState=ensureBaiBaiGroupState(target);if(!groupState.groups.some(g=>String(g.id)===String(groupId)))return;snapshotGroupChange(targetSide);if(!byId(targetSide).has(id)){const ord=state.cache.ordered[targetSide];let last=-1;for(let i=0;i<ord.length;i++){const gid2=groupState.prompts?.[ord[i].identifier]?.groupId;if(gid2&&String(gid2)===String(groupId))last=i;}const beforeId=last>=0&&last+1<ord.length?ord[last+1].identifier:null;movePrompt(sourceSide,targetSide,id,beforeId);}groupState.prompts[id]={groupId:String(groupId)};state.dirty[targetSide]=true;rebuildCache();renderList(targetSide);}
function togglePromptGroup(side,id){const grouping=state.grouping;if(grouping.side!==side||!grouping.groupId)return false;const groupState=ensureBaiBaiGroupState(state[side]),current=groupState.prompts?.[id]?.groupId;snapshotGroupChange(side);if(String(current||'')===String(grouping.groupId))delete groupState.prompts[id];else groupState.prompts[id]={groupId:String(grouping.groupId)};state.dirty[side]=true;renderList(side);return true;}
function finishGrouping(){state.grouping={side:null,groupId:null};renderAll();}
function onClick(event){if(performance.now()<suppressClickUntil)return;const target=event.target.closest('button');if(!target)return;const action=target.dataset.action;const groupElement=target.closest('.pcm-group');const groupId=groupElement?.dataset.groupId;const groupSide=groupElement?.dataset.groupSide||target.dataset.side;if(action==='submit-version'){document.querySelector('.pcm-inline-form[data-side="'+target.dataset.side+'"]')?.requestSubmit();}if(action==='choose-tavern')chooseTavernPreset(target.dataset.presetName);if(action==='close-picker')document.querySelector('[data-tavern-picker]')?.classList.remove('open');if(action==='new-group')newGroup(target.dataset.side);if(action==='rename-group')renameGroup(groupSide,groupId);if(action==='delete-group')deleteGroup(groupSide,groupId);if(action==='finish-group')finishGrouping();if(action==='toggle-uninjected'){const side=target.dataset.side;state.unInjectedCollapsed[side]=!state.unInjectedCollapsed[side];renderList(side);}if(action==='toggle-group'){const gk=target.dataset.groupKey;if(gk){state.groupCollapsed[gk]=!state.groupCollapsed[gk];renderList(target.dataset.side);}}if(action==='close'){if(typeof event.currentTarget.close==='function')event.currentTarget.close();else event.currentTarget.removeAttribute('open');}if(action==='export')exportPreset(target.dataset.side);if(action==='save-tavern')saveSideToTavern(target.dataset.side);if(action==='pull-tavern')pullTavernPreset();if(action==='save-project')saveProject();if(action==='save-changes'){if(state.projectId)saveProject(document.querySelector('[data-project-name]')?.value.trim());else saveProject();}if(action==='load-project'){const id=document.querySelector('[data-project-select]')?.value;if(id)loadProject(id);}if(action==='delete-project'){const id=document.querySelector('[data-project-select]')?.value;if(id)deleteProject(id);}if(action==='undo')undoLast();if(action==='collapse'){state.activeId=null;state.activeSide=null;if(state.freeSelect.enabled){state.freeSelect={enabled:true,oldId:null,newId:null};markFreeSelection();}hideCompare();renderAll();}if(action==='migrate')migrate(target.dataset.side);if(action==='duplicate-prompt')duplicatePrompt(target.dataset.side,target.dataset.id);if(action==='delete-prompt')deletePrompt(target.dataset.side,target.dataset.id);if(target.dataset.open){if(togglePromptGroup(target.dataset.side,target.dataset.open))return;state.activeId=target.dataset.open;state.activeSide=target.dataset.side;renderAll();}}
function onChange(event){if(event.target.dataset.file&&event.target.files[0])loadFile(event.target.dataset.file,event.target.files[0]);if(event.target.dataset.filter){const side=event.target.dataset.filter;state.filter[side]=event.target.value;renderList(side);}}
const searchTimers={old:null,new:null};
function onInput(event){if(event.target.dataset.search){const side=event.target.dataset.search;state.query[side]=event.target.value;clearTimeout(searchTimers[side]);searchTimers[side]=setTimeout(()=>renderList(side),150);}}
function openDialogSafe(dialog){applyUiTheme();try{if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');}catch(error){console.error('[preset-compare-migrator] open failed',error);dialog.setAttribute('open','');}}
function addMenu(){const menu=document.getElementById('extensionsMenu');if(!menu||document.getElementById(APP_ID+'-button'))return false;const entry=el('div','list-group-item flex-container flexGap5 interactable');entry.id=APP_ID+'-button';entry.tabIndex=0;entry.append(el('span','fa-solid fa-code-compare'),el('span','',APP_TITLE));entry.addEventListener('click',()=>{try{const d=shell();openDialogSafe(d);restorePanelState(d);}catch(error){console.error('[preset-compare-migrator] init failed',error);pcmToastr.error(error.message,APP_TITLE+'启动失败');}});menu.append(entry);return true;}
jQuery(()=>{loadUiPrefs();watchTavernPresetEvents();if(!addMenu()){const observer=new MutationObserver(()=>{if(addMenu())observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});}});
