// 正则内容表单：双击解锁文本、完整原生设置、显式保存；仅提交改变的字段。
export function createRegexEditor(script,{drafts,onSave}){
 const form=document.createElement('form');form.className='pcm-regex-edit-form';const draft=drafts.get(script)||{};const controls=new Map();
 const value=key=>Object.hasOwn(draft,key)?draft[key]:script[key];
 function field(label,key,type='text'){
  const box=document.createElement('label');box.className='pcm-regex-edit-field';const caption=document.createElement('span');caption.textContent=label;const input=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;if(type==='number'){input.min='-1';input.step='1';input.placeholder='不限';}input.name=key;input.value=type==='number'?(value(key)??''):key==='trimStrings'?(value(key)||[]).join('\n'):(value(key)??'');box.append(caption,input);controls.set(key,input);return box;
 }
 function check(label,key,parent,checked){const box=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name=key;input.checked=checked??!!value(key);box.append(input,document.createTextNode(label));parent.append(box);return input;}
 form.append(field('脚本名称','scriptName'));
 for(const [label,key] of [['查找正则表达式','findRegex'],['替换为','replaceString']]){const box=field(label,key,'textarea'),input=controls.get(key);box.classList.add('pcm-regex-'+key);input.readOnly=true;input.title='双击编辑；也可点击编辑按钮';const edit=document.createElement('button');edit.type='button';edit.textContent='编辑';edit.setAttribute('aria-label','编辑'+label);const unlock=()=>{input.readOnly=false;input.focus();};edit.addEventListener('click',unlock);input.addEventListener('dblclick',unlock);input.addEventListener('blur',()=>input.readOnly=true);box.firstChild.append(edit);form.append(box);}
 const details=document.createElement('details');details.className='pcm-regex-options';const summary=document.createElement('summary');summary.textContent='其他完整配置';details.append(summary,field('修剪掉（每行一项）','trimStrings','textarea'));
 const grid=document.createElement('div');grid.className='pcm-regex-options-grid';const placements=document.createElement('fieldset'),other=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent='作用范围';placements.append(legend);const known=[1,2,3,5,6],checks=known.map((id,i)=>[id,check(['用户输入','AI 输出','快捷命令','世界书','推理'][i],'placement',placements,(value('placement')||[]).includes(id))]);
 const bools={};for(const [key,label]of [['disabled','已禁用'],['runOnEdit','在编辑时运行'],['markdownOnly','仅影响显示'],['promptOnly','仅影响后端提示词']])bools[key]=check(label,key,other);
 const macro=document.createElement('label');macro.textContent='正则表达式中的宏';const select=document.createElement('select');select.name='substituteRegex';for(const [id,label]of [[0,'不替换'],[1,'替换（原始）'],[2,'替换（转义）']]){const o=new Option(label,String(id));select.append(o);}select.value=String(value('substituteRegex')??0);macro.append(select);controls.set('substituteRegex',select);other.append(macro);placements.append(field('最小深度','minDepth','number'),field('最大深度','maxDepth','number'));grid.append(placements,other);details.append(grid);form.append(details);
 const read=()=>{const result={};for(const [key,input]of controls){if(key==='trimStrings')result[key]=input.value.split('\n').filter(x=>x!=='');else if(['minDepth','maxDepth'].includes(key))result[key]=input.value===''?null:Number(input.value);else if(key==='substituteRegex')result[key]=Number(input.value);else result[key]=input.value;}for(const [key,input]of Object.entries(bools))result[key]=input.checked;result.placement=[...(script.placement||[]).filter(x=>!known.includes(x)),...checks.filter(([,input])=>input.checked).map(([id])=>id)];return result;};
 const baseline=read();const changed=new Set(Object.keys(draft));const remember=event=>{if(event.target.name)changed.add(event.target.name);const current=read(),patch={};for(const key of changed)patch[key]=current[key];drafts.set(script,patch);};form.addEventListener('input',remember);form.addEventListener('change',remember);
 const save=document.createElement('button');save.type='submit';save.textContent='保存正则';save.className='pcm-primary';const status=document.createElement('span');status.setAttribute('role','status');form.append(save,status);form.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation();try{const current=read(),patch={};for(const key of changed)if(JSON.stringify(current[key])!==JSON.stringify(baseline[key])||Object.hasOwn(draft,key))patch[key]=current[key];onSave(patch);drafts.delete(script);status.textContent='已保存到预设草稿';}catch(error){status.textContent=error.message;}});return form;
}
