// 整组迁移回归：分组边界、跨侧合并、字段和来源保留。
import test from 'node:test';
import assert from 'node:assert/strict';
import { transferPresetGroup } from '../src/features/preset/group-transfer.js';
const fixture=()=>({prompts:['a','b','c','d','u'].map(identifier=>({identifier,content:identifier,extra:{keep:true}})),prompt_order:[{character_id:100001,order:['a','b','c','d','u'].map(identifier=>({identifier,enabled:identifier!=='b',extra:8}))}],extensions:{other:9,baibaiToolkit:{presetPromptGroups:{extra:10,groups:[{id:'g',name:'G',enabled:false,collapsed:true,extra:11},{id:'h',name:'H'}],prompts:{a:{groupId:'g',extra:12},b:{groupId:'g'},c:{groupId:'h'},d:{groupId:'h'}}}}}});
const ids=p=>p.prompt_order[0].order.map(x=>x.identifier||x);
test('same-side whole group sorts atomically at a boundary without mutating input',()=>{const p=fixture(),before=JSON.stringify(p);const r=transferPresetGroup(p,p,'g','u');assert.deepEqual(ids(r),['c','d','a','b','u']);assert.equal(JSON.stringify(p),before);assert.equal(r.prompts.find(x=>x.identifier==='a'),p.prompts[0]);assert.equal(r.prompt_order[0].order[3].enabled,false);assert.equal(r.extensions.other,9)});
test('rejects a landing inside another group or at a stale id',()=>{const p=fixture();assert.throws(()=>transferPresetGroup(p,p,'g','d'),/分组/);assert.throws(()=>transferPresetGroup(p,p,'g','gone'));});
test('cross side keeps originals and generates independent group/member IDs on collision',()=>{const p=fixture(),t=fixture();const before=JSON.stringify(p);const r=transferPresetGroup(p,t,'g',null);assert.deepEqual(ids(r).slice(0,5),ids(t));assert.equal(ids(r).length,7);assert.equal(new Set(ids(r)).size,7);const group=r.extensions.baibaiToolkit.presetPromptGroups.groups.find(g=>g.name==='G（1）');assert(group);assert.notEqual(group.id,'g');assert.equal(group.extra,11);const copies=r.prompts.filter(x=>!t.prompts.some(y=>y.identifier===x.identifier));assert.equal(copies.length,2);assert.deepEqual(copies.map(p=>p.content),['a','b']);assert.equal(r.extensions.baibaiToolkit.presetPromptGroups.prompts[copies[0].identifier].extra,12);assert.equal(JSON.stringify(p),before);assert.equal(r.extensions.baibaiToolkit.presetPromptGroups.prompts.a.groupId,'g');});
test('same names with different ids remain separate and uninjected members remain uninjected',()=>{const p=fixture(),t=fixture();p.prompts.push({identifier:'hidden',content:'x'});p.extensions.baibaiToolkit.presetPromptGroups.prompts.hidden={groupId:'g'};t.extensions.baibaiToolkit.presetPromptGroups.groups[1].name='G';const r=transferPresetGroup(p,t,'g','c');assert.equal(r.extensions.baibaiToolkit.presetPromptGroups.groups.length,3);assert(r.prompts.some(x=>x.identifier==='hidden'));assert(!ids(r).includes('hidden'));});


test('duplicate group names increment while a free prompt ID is retained',()=>{const p=fixture(),t=fixture();t.extensions.baibaiToolkit.presetPromptGroups.groups.push({id:'taken',name:'G（1）'});p.prompts[0].identifier='fresh';p.prompt_order[0].order[0].identifier='fresh';p.extensions.baibaiToolkit.presetPromptGroups.prompts.fresh={groupId:'g'};const r=transferPresetGroup(p,t,'g',null);assert(r.extensions.baibaiToolkit.presetPromptGroups.groups.some(g=>g.name==='G（2）'));assert(ids(r).includes('fresh'));});
test('presets without explicit order retain existing visible entries when copied or sorted',()=>{const p=fixture(),t=fixture();delete p.prompt_order;t.prompt_order=[];const r=transferPresetGroup(p,t,'g','c');assert.deepEqual(ids(r).slice(0,2),['a','b']);assert.equal(ids(r).length,7);assert(ids(r).includes('u'));const q=transferPresetGroup(p,p,'g','u');assert.deepEqual(ids(q),['c','d','a','b','u']);});
