// 正则编辑与柏宝箱元数据回归：保留未知字段、无关分组和执行顺序。
import test from 'node:test';
import assert from 'node:assert/strict';
import {editRegexScript,groupRegexScripts,deleteRegexScripts,renameRegexGroup,removeRegexGroup} from '../src/features/preset/regex-edit.js';
const fixture=()=>({extensions:{untouched:7,regex_scripts:[{id:'a',scriptName:'A',findRegex:'/a/g',replaceString:'x\r\ny',placement:[2,99],unknown:{x:1}},{id:'b',scriptName:'B'},{id:'c',scriptName:'C'}],baibaiToolkit:{other:9}}});
test('regex edits patch only exposed fields and preserve raw text',()=>{const p=fixture();editRegexScript(p,0,{findRegex:'/b/g',replaceString:'\r\n$1',minDepth:0});assert.equal(p.extensions.regex_scripts[0].replaceString,'\r\n$1');assert.deepEqual(p.extensions.regex_scripts[0].unknown,{x:1});assert.deepEqual(p.extensions.regex_scripts[0].placement,[2,99]);assert.throws(()=>editRegexScript(p,9,{}));assert.throws(()=>editRegexScript(p,0,{minDepth:-2}));});
test('group writes version 1 metadata, preserves script execution order and other extensions',()=>{const p=fixture();const id=groupRegexScripts(p,[2,0],'组');const g=p.extensions.baibaiToolkit.regexGroups;assert.equal(g.version,1);assert.equal(g.scripts.a.groupId,id);assert.equal(g.scripts.a.order,0);assert.equal(g.scripts.c.order,1);assert.deepEqual(p.extensions.regex_scripts.map(x=>x.id),['a','b','c']);assert.equal(p.extensions.baibaiToolkit.other,9);renameRegexGroup(p,id,'新组');assert.equal(g.groups[0].name,'新组');removeRegexGroup(p,id);assert.equal(g.groups.length,0);assert.equal(p.extensions.regex_scripts.length,3);});
test('batch delete clears only corresponding metadata and retains survivors',()=>{const p=fixture();groupRegexScripts(p,[0,1],'组');deleteRegexScripts(p,[0,2]);assert.deepEqual(p.extensions.regex_scripts.map(x=>x.id),['b']);assert.equal(p.extensions.baibaiToolkit.regexGroups.scripts.a,undefined);assert(p.extensions.baibaiToolkit.regexGroups.scripts.b);assert.equal(p.extensions.untouched,7);});
test('native minus-one depth sentinel remains editable and blank removes limits',()=>{const p=fixture();Object.assign(p.extensions.regex_scripts[0],{minDepth:0,maxDepth:-1});editRegexScript(p,0,{scriptName:'改名'});editRegexScript(p,0,{minDepth:-1});assert.equal(p.extensions.regex_scripts[0].maxDepth,-1);editRegexScript(p,0,{minDepth:null,maxDepth:null});assert.equal(p.extensions.regex_scripts[0].maxDepth,null);});
